### PR TITLE
fix: rewrite model name in response body to match client-facing name

### LINKED ISSUE #1625: Bug: Response body leaks internal target model name instead of rewriting to original
The Gateway implements a model rewrite feature to abstract internal backend models (e.g., `vllm-backend-01`) behind a public alias (e.g., `gpt-4-proxy`).
*   **Request:** The Gateway correctly rewrites the request body: `req.Body["model"] = "vllm-backend-01"`.
*   **Response:** The Gateway fails to perform the reverse rewrite. The response body is passed through directly from the backend to the client.

**Root Cause Analysis (RCA)**:
*   **`handlers/response.go`**: `HandleResponseBody` marshals the raw `response map[string]any` without intercepting the `model` key.
*   **`handlers/server.go`**: The streaming handler (`ProcessingRequest_ResponseBody`) performs a raw byte passthrough of chunks, failing to inspect or mutate the model name in the SSE stream.

**Impact**:

This may violate client assumptions. Clients expecting the public model name will receive the internal name, causing client-side validation errors and leaking infrastructure details.

**Recommended Fix**:
1.  **Standard:** In `HandleResponseBody`, explicitly set `response["model"] = reqCtx.IncomingModelName` before marshaling.
2.  **Streaming:** Implement a parser for the first/last SSE chunks to rewrite the model field in the JSON payload.

### PR DESCRIPTION
**Pull request by gyliu513**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/kind bug
fixed #1625 
/cc @kfswain @LukeAVanDrie

### CODE REVIEW

**Comment by nirrozenbaum** [comment]
/ok-to-test

@gyliu513 good catch!

/cc @zetxqx can have a look?

File: pkg/epp/handlers/server.go [hunk 1]
```diff
@@ -337,11 +340,33 @@ func (s *StreamingServer) finishResponse(ctx context.Context, reqCtx *RequestCon
...
+	new := []byte(`"model":"` + incomingModel + `"`)
+	result := bytes.ReplaceAll(body, old, new)
+	if !bytes.Equal(result, body) {
+		return result
+	}
+	// Also handle the case where JSON has spaces after the colon: "model": "..."
+	old = []byte(`"model": "` + targetModel + `"`)
+	new = []byte(`"model": "` + incomingModel + `"`)
+	return bytes.ReplaceAll(body, old, new)
+}
```
Comment (ahg-g) [inline pkg/epp/handlers/server.go:368]: @zetxqx this needs to be handled in a parser specific way just like the model re-write

Comment (zetxqx) [reply pkg/epp/handlers/server.go:368]: Yes, will do it in the #2692

**Comment by zetxqx** [comment]
looks good to me, thank you!

/lgtm
