### PR TITLE
Unit test fixes - Add missing test cases for new datalayer metrics.

### LINKED ISSUE #2638: Break down data layer and metrics changes into smaller PRs
This issue tracks the breakdown of a previously large [PR](https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/2590) into smaller, focused changes to improve review-ability and reduce risk.

Planned PRs:

- [ ] Automatically add `Data` section when data layer is enabled.
- [ ] Unit test fixes - Add missing test cases for new datalayer metrics.
- [ ] E2E improvements: CRD existence validation and cluster/context logging,
- [ ] Add Datalayer Integration tests and `harness.go` refactor.
- [ ] Enable data layer by default.

Each PR will be submitted and reviewed independently.

### PR DESCRIPTION
**Pull request by Mohamedma96**
### Summary
Adds missing unit test coverage for datalayer metrics.

### Changes
- Introduced test cases to validate datalayer metrics behavior
- Covered scenarios that were previously untested
- Improved overall test completeness and reliability

### Impact
- No changes to production code
- Improves confidence in metrics-related functionality

### Notes
This PR is part of a larger effort to improve test coverage and stabilize datalayer functionality.

**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
Recent changes introduced new datalayer metrics without sufficient unit test coverage. This PR ensures these paths are properly validated and reduces the risk of regressions.

**Which issue(s) this PR fixes**:

Partially Fixes #2638 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/epp/backend/metrics/pod_metrics_test.go
Comment (elevran) [inline pkg/epp/backend/metrics/pod_metrics_test.go:1]: nit: questionable if it is worth investing in updating the backend/metrics tests.
Might have been easier to confirm that the functionality test exist and passes on datalayer only.

File: pkg/epp/backend/metrics/pod_metrics_test.go [hunk 1]
```diff
@@ -60,28 +61,65 @@ var (
...
+		setupFn func(t *testing.T) (datalayer.EndpointFactory, func(map[types.NamespacedName]*MetricsState))
+	}{
+		{
+			name: "Legacy PodMetricsFactory",
+			setupFn: func(t *testing.T) (datalayer.EndpointFactory, func(map[types.NamespacedName]*MetricsState)) {
+				pmc := &FakePodMetricsClient{}
+				pmf := NewPodMetricsFactory(pmc, interval)
+				setMetrics := func(m map[types.NamespacedName]*MetricsState) {
+					pmc.SetRes(m)
+				}
```
Comment (elevran) [inline pkg/epp/backend/metrics/pod_metrics_test.go]: no need for closure

```suggestion
				setMetrics := pmc.SetRes
```

File: pkg/epp/datastore/datastore.go [hunk 2]
```diff
@@ -333,6 +333,9 @@ func (ds *datastore) podUpdateOrAddIfNotExist(ctx context.Context, pod *corev1.P
 		existing, ok := ds.pods.Load(endpointMetadata.NamespacedName)
 		if !ok {
 			ep = ds.epf.NewEndpoint(ds.parentCtx, endpointMetadata, ds)
+			if ep == nil {
+				continue
+			}
```
Comment (elevran) [inline pkg/epp/datastore/datastore.go:341]: silently skips creating an endpoint with no comment explaining when `NewEndpoint` can return nil. Agree that not adding a nil endpoint makes sense but wonder why this was needed (e.g., can it really fail in production or is it a test case code that's checking something?)

File: pkg/epp/framework/plugins/datalayer/source/mocks/data_source_mock.go [hunk 3]
```diff
@@ -56,8 +58,17 @@ func (fds *MetricsDataSource) ExtractorType() reflect.Type {
 func (fds *MetricsDataSource) Extractors() []string                 { return []string{} }
 func (fds *MetricsDataSource) AddExtractor(_ fwkdl.Extractor) error { return nil }
```
Comment (elevran) [inline pkg/epp/framework/plugins/datalayer/source/mocks/data_source_mock.go]: Are these still needed after the runtime / interface separation?
If not, please clean up other occurrences of interface functions that have been refactored.

File: pkg/epp/framework/plugins/datalayer/source/mocks/data_source_mock.go [hunk 4]
```diff
@@ -56,8 +58,17 @@ func (fds *MetricsDataSource) ExtractorType() reflect.Type {
...
+// SetMetrics replaces the Metrics map in a thread-safe manner.
+func (fds *MetricsDataSource) SetMetrics(metrics map[types.NamespacedName]*fwkdl.Metrics) {
+	fds.mu.Lock()
+	defer fds.mu.Unlock()
+	fds.Metrics = metrics
+}
+
 func (fds *MetricsDataSource) Poll(ctx context.Context, ep fwkdl.Endpoint) (any, error) {
 	atomic.AddInt64(&fds.CallCount, 1)
+	fds.mu.RLock()
```
Comment (elevran) [inline pkg/epp/framework/plugins/datalayer/source/mocks/data_source_mock.go:74]: The mutex coverage is asymmetric.
The code holds `mu.RLock()` when reading metrics and errors, but there's no `SetErrors` mirror of `SetMetrics` that can sync on the mutex. Any test that assigns `fds.Errors = ...` concurrently with polling will still race.

File: pkg/epp/backend/metrics/pod_metrics_test.go
Comment (Mohamedma96) [reply pkg/epp/backend/metrics/pod_metrics_test.go:1]: I don't think it is actually worth the hassle, since the goal is to enable datalayer by default, we already have the unit tests for the datalayer, maybe keeping the current files as is so they can be testing the legacy tests is fine (until we take down the backend/metrics).

File: pkg/epp/datastore/datastore.go (hunk 2 above)
Comment (Mohamedma96) [reply pkg/epp/datastore/datastore.go:341]: nil is retruned in NewEndpoint only if there is a collector for that endpoint, and there is a log in NewEndpoint for that case.

File: pkg/epp/framework/plugins/datalayer/source/mocks/data_source_mock.go (hunk 3 above)
Comment (Mohamedma96) [reply pkg/epp/framework/plugins/datalayer/source/mocks/data_source_mock.go]: no they are not needed anymore, runtime.go handles the extractors

File: pkg/epp/framework/plugins/datalayer/source/mocks/data_source_mock.go (hunk 4 above)
Comment (Mohamedma96) [reply pkg/epp/framework/plugins/datalayer/source/mocks/data_source_mock.go:74]: correct, added also SetErrors and used mutex there.

File: pkg/epp/backend/metrics/pod_metrics_test.go (hunk 1 above)
Comment (Mohamedma96) [reply pkg/epp/backend/metrics/pod_metrics_test.go]: done

File: pkg/epp/framework/plugins/datalayer/source/mocks/data_source_mock.go (hunk 3 above)
Comment (Mohamedma96) [reply pkg/epp/framework/plugins/datalayer/source/mocks/data_source_mock.go]: done

File: pkg/epp/datastore/datastore.go (hunk 2 above)
Comment (elevran) [reply pkg/epp/datastore/datastore.go:341]: then a comment here can be helpful

File: pkg/epp/backend/metrics/pod_metrics_test.go
Comment (elevran) [reply pkg/epp/backend/metrics/pod_metrics_test.go:1]: @Mohamedma96 what's the resolution then? keep or delete?

**Comment by Mohamedma96** [comment]
> /lgtm /hold
> 
> @Mohamedma96 leaving hold in case you want to remove pod_metrics_test.go from the PR or add the comment on datastore.go

both done.
