### PR TITLE
fix: log correct error from Prepare Data Plugins

### LINKED ISSUE #2508: Director: Prepare-plugin error logged incorrectly
- **Location**: `pkg/epp/requestcontrol/director.go` in HandleRequest()

- **Symptom**: `runPrepareDataPlugins(...)`'s error is ignored, but the logger call uses a stale `err` variable:
  - Existing line: `logger.V(logutil.DEFAULT).Error(err, "failed to prepare per request data")`
 
- **Impact**: The actual prepare-plugin error is not captured or logged, producing misleading logs (and risking use of an unrelated/undefined err). This harms observability and debugging.

- **Proposed fix**: Capture the returned error and log it. Example patch:
  ```
  if prepErr := d.runPrepareDataPlugins(ctx, reqCtx.SchedulingRequest, snapshotOfCandidatePods); prepErr != nil {
      logger.V(logutil.DEFAULT).Error(prepErr, "failed to prepare per-request data")
  }
  ```

**Optional improvement**: Record a plugin-failure metric when `prepErr != nil` to aid alerting/telemetry.

### PR DESCRIPTION
**Pull request by varad-ahirwadkar**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
`HandleRequest()` ignored the error returned by `runPrepareDataPlugins` and logged a stale `err` variable, causing misleading logs. 
Capture and log the actual returned error to improve observability.

**Which issue(s) this PR fixes**:

Fixes  #2508

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

File: pkg/epp/requestcontrol/director.go [hunk 1]
```diff
@@ -166,9 +166,10 @@ func (d *Director) HandleRequest(ctx context.Context, reqCtx *handlers.RequestCo
 	snapshotOfCandidatePods := d.toSchedulerPodMetrics(candidatePods)
 
 	// Prepare per request data by running PrepareData plugins.
-	if d.runPrepareDataPlugins(ctx, reqCtx.SchedulingRequest, snapshotOfCandidatePods) != nil {
+	prepErr := d.runPrepareDataPlugins(ctx, reqCtx.SchedulingRequest, snapshotOfCandidatePods)
```
Comment (nirrozenbaum) [inline pkg/epp/requestcontrol/director.go]: can you reuse err instead of introducing a new var?

Comment (varad-ahirwadkar) [reply pkg/epp/requestcontrol/director.go]: sure!
