### PR TITLE
make ModelName immutable and fix model weight

### LINKED ISSUE #408: Make ModelName immutable
**What would you like to be added**:

Make ModelName in InferenceModel immutable. 

While we can't do this using CEL, we can add ValidatingAdmissionPolicy as part of the CRD installation. 

**Why is this needed**:

ModelName for a specific InferenceModel should not change. We had to add ModelName as a separate parameter instead of using the object name because the model name can be arbitrary and more flexible than k8s object names.

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Fix https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/426

Fix #408

### CODE REVIEW

File: api/v1alpha2/inferencemodel_types.go [hunk 1]
```diff
@@ -175,7 +176,7 @@ type TargetModel struct {
 	// Conversely weights are optional, so long as ALL targetModels do not specify a weight.
 	//
 	// +optional
-	// +kubebuilder:validation:Minimum=0
+	// +kubebuilder:validation:Minimum=1
```
Comment (hzxuzhonghu) [inline api/v1alpha2/inferencemodel_types.go:179]: It set to 0, it will panic too

Comment (Kuromesi) [reply api/v1alpha2/inferencemodel_types.go:179]: Can we allow to set 0 weight which users can do so to disabled the model instead of removing the model?

Comment (robscott) [reply api/v1alpha2/inferencemodel_types.go:179]: A similar question came up in Gateway API and we ultimately decided that we'd rather have people remove the backend altogether to avoid any confusion. In practice this likely just means commenting out some YAML. I'd prefer to follow the same pattern here.

**Comment by robscott** [comment]
Thanks @hzxuzhonghu!

/lgtm
