### PR TITLE
Limit response body size

### LINKED ISSUE #2056: BBR causes RESOURCE_EXHAUSTED in envoy when sending large request(> 30k chars)
**What happened**:
When enabled BBR, sending large request(>30k chars) will get 500 internal error.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
You should have a IGW stack with BBR enabled. Send request with 30k chars.

**Anything else we need to know?**:

The root cause is BBR is sending the whole (buffered) response body in one go(https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/pkg/bbr/handlers/request.go#L127) We should change it to send chunked `ProcessingResponse_RequestBody` as we did in EPP(https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/55f5e446b10ee41100c2497cdd61539d2ac7325f/pkg/epp/handlers/request.go#L78)

### PR DESCRIPTION
**Pull request by adelsam**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
BBR accumulates the request body (required for JSON deserialization). Similar to EPP, this request is echoed back to Envoy. This change extracts the common BuildChunkedBodyResponses functionality and refactors both EPP and BBR to use it. As a result, BBR will now send a chunked request_response back to Envoy, preventing the RESOURCE_EXHAUSTED error for large requests.

**Which issue(s) this PR fixes**:

Fixes #2056 

**Does this PR introduce a user-facing change?**:

```release-note
improved support for large request payloads when BBR is enabled.
```

### CODE REVIEW

**Comment by ahg-g** [comment]
/ok-to-test

Thanks for the fix, you need to sign the cla as well

**Comment by ahg-g** [comment]
@kfswain shouldn't we have the same approach in both epp and bbr for this?

**Comment by kfswain** [comment]
Yeah, we have that same const in the EPP ext-proc, for this PR, can we have them use the same const? A follow up issue would be to provide all the ext-proc scaffolding as a distinct module, so EPP/BBR get the same benefits and we have much less copy/paste. Preventing issues like this.

**Comment by nirrozenbaum** [comment]
@ahg-g @kfswain other than avoiding code duplication that can be done in a followup, is anything blocking us on getting this merged?

/lgtm
leaving final stamp to my friends here.

File: pkg/common/chunking.go [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+
+package common
+
+import (
+	extProcPb "github.com/envoyproxy/go-control-plane/envoy/service/ext_proc/v3"
+)
+
+// BuildChunkedBodyResponses splits the bodyBytes into chunks of size byteLimit and returns a slice of CommonResponse.
+// If setEos is true, the last chunk will have EndOfStream set to true.
+func BuildChunkedBodyResponses(bodyBytes []byte, byteLimit int, setEos bool) []*extProcPb.CommonResponse {
```
Comment (zetxqx) [inline pkg/common/chunking.go]: do we want to also centralize the `bodyLimit` const here in this file?

Comment (adelsam) [reply pkg/common/chunking.go]: sure!

**Comment by zetxqx** [comment]
/lgtm

tysm!

**Comment by kfswain** [comment]
/approve

Nope, this is great. Thanks!
