### PR TITLE
Config options fix

### LINKED ISSUE #2297: Segmentation fault when config file or config text is not configured
**What happened**:

When the EPP is spun up without the `--config-text` or `--config-file` options configured, no raw config is returned here in `ParseConfigurationPhaseOne()`:

https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/81dc82393e4f387b31a5d5a9e12ccf3ce6f41baa/cmd/epp/runner/runner.go#L400-L403

If I'm interpreting `configuring through code, not through file` right, then excluding the config should be valid and some default should be used for the config instead.

In `ParseConfigurationPhaseTwo()`, the `rawConfig` returned from phase one is passed into the config loader, where we hit a segmentation fault when it attempts to access `rawConfig.plugins` (from a nil value):

https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/81dc82393e4f387b31a5d5a9e12ccf3ce6f41baa/cmd/epp/runner/runner.go#L454

https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/81dc82393e4f387b31a5d5a9e12ccf3ce6f41baa/pkg/epp/config/loader/configloader.go#L83

The error:

```
goroutine 1 [running]:
sigs.k8s.io/gateway-api-inference-extension/pkg/epp/config/loader.LoadConfigPhaseTwo(0x0, {0x28552a8, 0xc000645290}, {{0x2855d88?, 0xc000645230?}, 0xc0006451d0?})
        /src/pkg/epp/config/loader/configloader.go:70 +0x49
sigs.k8s.io/gateway-api-inference-extension/cmd/epp/runner.(*Runner).parseConfigurationPhaseTwo(0xc00023bf00, {0x284d528, 0xc000642d70}, 0x0, {0x2860798, 0xc0009529c0})
        /src/cmd/epp/runner/runner.go:452 +0x19c
sigs.k8s.io/gateway-api-inference-extension/cmd/epp/runner.(*Runner).Run(0xc00023bf00, {0x284d528, 0xc000642d70})
        /src/cmd/epp/runner/runner.go:236 +0x4fa
main.main()
        /src/cmd/epp/main.go:31 +0xd5
```

**What you expected to happen**:

I'd expect for the EPP to function without a config provided via `--config-text` or `--config-file`.

**How to reproduce it (as minimally and precisely as possible)**:

This is the yaml I am currently using where the EPP fails to come up:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-endpoint-picker
  namespace: inference-model-server
  labels:
    app: inference-epp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-epp
  template:
    metadata:
      labels:
        app: inference-epp
    spec:
      containers:
      - name: epp
        image: us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension/epp:v20251119-2aaf2a6
        imagePullPolicy: Always
        args:
        - --pool-name
        - "inference-model-server-pool"
        - --pool-namespace
        - "inference-model-server"
        - --v
        - "4"
        - --zap-encoder
        - "json"
        ports:
        - containerPort: 9002
        - containerPort: 9003
        - name: metrics
          containerPort: 9090
        livenessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
```

**Anything else we need to know?**:

I could help fix this if I'm correct in thinking this is a bug, but just curious what the expected behavior is supposed to be.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Inference extension version (use `git describe --tags --dirty --always`): v1.0.1 (I'm using an EPP image from November though).
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by shmuelk**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
A textual configuration is required by the EPP to run.

If neither the config-text nor the config-file options are specified, the EPP crashes with a nil pointer error.

This PR adds to the options validation code a check that one of the config-text or config-file command line arguments has been specified.

In addition this PR adds a very simple log setup for the initial log messages issued before the command line arguments parse and validate correctly. Without this, no error messages show up in the EPP's stdout. See https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/log#hdr-The_Log_Handle for more details.

**Which issue(s) this PR fixes**:
Fixes #2297

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/epp/server/options.go [hunk 1]
```diff
@@ -228,6 +228,9 @@ func (opts *Options) Validate() error {
 		}
 	}
 
+	if opts.ConfigText == "" && opts.ConfigFile == "" {
```
Comment (elevran) [inline pkg/epp/server/options.go:231]: Q: is it (or should it be) possible to run EPP without a configuration file? There are runner options that set config directly in code (`With...()`). Sould the validation also check the configuration pointers on the runner?

Comment (ahg-g) [reply pkg/epp/server/options.go:231]: Ideally we should have a default configuration. I think in general our config defaulting, especially the way individual plugins config defaulting is done needs re-work.

Comment (nirrozenbaum) [reply pkg/epp/server/options.go:231]: practically atm we provide default plugins for certain extension points.
we don't provide default configuration if non was specified.
as an immediate fix for the segfault this looks good from my side.
longer term I agree default configuration would be a nicer solution.

**Review by nirrozenbaum — APPROVED** [review]
/lgtm
/approve

holding in case @elevran or @ahg-g have more comments.
if not please unhold.
/hold

File: pkg/epp/server/options.go (hunk 1 above)
Comment (shmuelk) [reply pkg/epp/server/options.go:231]: The current With...() functions of the runner do not set enough configuration related stuff.

When the datalayer goes production, there will be more work done.

**Comment by shmuelk** [comment]
I have created issue #2324 to discuss and track the adding of a default configuration for the EPP.
