### PR TITLE
[pluggable parser] add AppProtocol validation in the InferencePool Reconcile loop

### LINKED ISSUE #2750: [pluggable parser] EPP should fail at startup on InferencePool appProtocol and gRPC parser mismatch
Currently, EPP does not strictly validate the alignment between the InferencePool configuration and the internal parser settings during the startup sequence.

Since EPP watches the `InferencePool`, it has direct visibility into the underlying `appProtocol`. If an operator configures a gRPC parser (via `EndpointPickerConfig.parser`) but the InferencePool defines a conflicting or incompatible appProtocol, the system may start in an inconsistent state, leading to difficult-to-debug runtime errors.

Proposed Behavior:

EPP should perform a validation check during its initialization phase:
* Inspect the appProtocol defined in the InferencePool. Compare this protocol against the configured parser (e.g., ensuring a gRPC parser is only used when the protocol is gRPC-compatible).
* Fail Fast: If a mismatch is detected, EPP should log a clear error message describing the conflict and terminate the startup process.

### PR DESCRIPTION
**Pull request by zetxqx**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
Add `AppProtocolValidator` interface for parsers to implement optionally.

The validation is done in the`health.go` loop. If a mismatch is detected, the health server will return non_serving

I didn't put the validation in startup because inferencePool may installed after the EPP start. Adding to the reconcile loop will  prevent some early failure when inferencePool is installed later.

**Which issue(s) this PR fixes**:

Fixes #2750

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/epp/controller/inferencepool_reconciler.go [hunk 1]
```diff
@@ -87,6 +89,23 @@ func (c *InferencePoolReconciler) Reconcile(ctx context.Context, req ctrl.Reques
 		return ctrl.Result{}, fmt.Errorf("unsupported API group: %s", c.PoolGKNN.Group)
 	}
 
+	if c.Validator != nil {
```
Comment (ahg-g) [inline pkg/epp/controller/inferencepool_reconciler.go]: I think we should do this in the epp health check: https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/cmd/epp/runner/health.go#L47; return not healthy if the configured parser doesn't support the appProtocol.

File: pkg/epp/framework/plugins/requesthandling/parsers/vllmgrpc/vllmgrpc.go [hunk 2]
```diff
@@ -75,6 +77,13 @@ func (p *VllmGRPCParser) TypedName() fwkplugin.TypedName {
 	return p.typedName
 }
 
+func (p *VllmGRPCParser) ValidateAppProtocol(appProtocol v1.AppProtocol) error {
```
Comment (ahg-g) [inline pkg/epp/framework/plugins/requesthandling/parsers/vllmgrpc/vllmgrpc.go]: Instead of placing the burden of validation on the plugin, the plugin should just return the list of protocols  it supports and then the caller validates if that matches the value declared on the infPool. 

We should have a special `match all` value, perhaps an empty list, so that plugins like the passthrough one can return to signify that all protocols are supported.

**Comment by ahg-g** [comment]
@zetxqx can w please finalize this?

File: pkg/epp/framework/plugins/requesthandling/parsers/vllmgrpc/vllmgrpc.go (hunk 2 above)
Comment (zetxqx) [reply pkg/epp/framework/plugins/requesthandling/parsers/vllmgrpc/vllmgrpc.go]: great suggestion, updated.

for the `match all` value, currently I made the `AppProtocolSupporter` a separate interface from the parser interface. So that parser can select not implementing `AppProtocolSupporter`, not implementing is also considered to be `match all`

File: pkg/epp/controller/inferencepool_reconciler.go (hunk 1 above)
Comment (zetxqx) [reply pkg/epp/controller/inferencepool_reconciler.go]: great point, moved the check to health.go

File: hack/verify-framework-imports.go [hunk 3]
```diff
@@ -127,6 +127,15 @@ var currentCodeExceptionMap = map[string][]string{
 	"pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/plugin.go": {
 		"pkg/epp/metrics",
 	},
+	"pkg/epp/framework/interface/requesthandling/plugins.go": {
+		"api/v1",
```
Comment (ahg-g) [inline hack/verify-framework-imports.go]: add this to `globalExceptions` above instead of listing it for each, this is fine to have a dependency on for any file.

File: pkg/epp/framework/interface/requesthandling/plugins.go [hunk 4]
```diff
@@ -43,3 +44,9 @@ type ParsedResponse struct {
 	// Usage is only populate when the raw response has usage.
 	Usage *requestcontrol.Usage
 }
+
+// AppProtocolSupporter is an optional interface that parsers can implement to specify
+// the list of supported protocols.
```
Comment (ahg-g) [inline pkg/epp/framework/interface/requesthandling/plugins.go]: I recommend to make it mandatory, meaning just have the `SupportedAppProtocols() []v1.AppProtocol` as part of the `Parser` plugin interface.

File: hack/verify-framework-imports.go (hunk 3 above)
Comment (zetxqx) [reply hack/verify-framework-imports.go]: done

File: pkg/epp/framework/interface/requesthandling/plugins.go (hunk 4 above)
Comment (zetxqx) [reply pkg/epp/framework/interface/requesthandling/plugins.go]: updated
