### PR TITLE
fix inference extension not correctly scrape pod metrics

### LINKED ISSUE #365: inference extension not correctly scrape pod metrics
**What happened**:
Currently inference extension request `url := fmt.Sprintf("http://%s/metrics", existing.Address)` for metrics, however, in the latest version, pod address is the pod ip and the port is not assigned to the url, so inference extension can not correctly scrape the pod metrics since it always send requests to port 80.

```go
new := &PodMetrics{
		Pod: Pod{
			NamespacedName: types.NamespacedName{
				Name:      pod.Name,
				Namespace: pod.Namespace,
			},
			Address: pod.Status.PodIP,
		},
		Metrics: Metrics{
			ActiveModels: make(map[string]int),
		},
	}
```

And also, the scrape time is `refreshMetricsInterval           = flag.Duration("refreshMetricsInterval", 50*time.Millisecond, "interval to refresh metrics via polling pods")`. So once the metrics fail to be scraped, the resulting logs can become quite extensive.

Image

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Inference extension version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Kuromesi**
resolve #365

### CODE REVIEW

File: pkg/ext-proc/backend/vllm/metrics.go [hunk 1]
```diff
@@ -45,7 +45,7 @@ func (p *PodMetricsClientImpl) FetchMetrics(
 
 	// Currently the metrics endpoint is hard-coded, which works with vLLM.
 	// TODO(https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/16): Consume this from InferencePool config.
-	url := fmt.Sprintf("http://%s/metrics", existing.Address)
+	url := existing.BuildScrapeEndpoint()
```
Comment (ahg-g) [inline pkg/ext-proc/backend/vllm/metrics.go:48]: Can we just pass in the port number to the function and have the caller get the port number from the pool directly instead of adding the port to every pod?

Comment (Kuromesi) [reply pkg/ext-proc/backend/vllm/metrics.go:48]: Yes but I did like this for considerations as:
- I think during the lifetime of a pod, the scrape port or path should not change, and I think it is reasonable to store this info in PodMetrics.
- If we pass the port to `FetchMetrics`, we may call `datastore.PoolGet()` to get the targetPort, this will try to acuire the pool lock every 50 milliseconds, I think this may affect the performance (but not tested).

I can rewrite the code if you think this considerations are not reasonable. 🤔

Comment (ahg-g) [reply pkg/ext-proc/backend/vllm/metrics.go:48]: ok, thanks for looking into it! btw https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/363 will merge first, so we will need to rebase this PR unfortunately since the `ext-proc/backend/types.go` will move to `ext-proc/datastore/types.go`.

Comment (Kuromesi) [reply pkg/ext-proc/backend/vllm/metrics.go:48]: Got it, thanks for you comments!

Comment (ahg-g) [reply pkg/ext-proc/backend/vllm/metrics.go:48]: The PR merged now, pls rebase when you get a chance.

**Comment by kfswain** [comment]
This looks great! I like abstracting the scrape path as well! 
Thanks for the catch also. Will LGTM when we get the rebase

File: pkg/ext-proc/backend/vllm/metrics.go (hunk 1 above)
Comment (Kuromesi) [reply pkg/ext-proc/backend/vllm/metrics.go:48]: done!

Comment (ahg-g) [reply pkg/ext-proc/backend/vllm/metrics.go:48]: btw the lock is a read lock, so it shouldn't add any overhead, but this is fine too.

**Review by ahg-g — COMMENTED** [review]
/approve

Thanks again, this highlights the limitation of our e2e testing! I had verified the metrics in [the ](https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/350); but this change that moved the port out of the address was done in a second to last commit in that PR and so wasn't manually verified :(
