### PR TITLE
controller: extend flow lease scope to fix orphaned queues #1982

### LINKED ISSUE #1982: Rare Race Condition: Premature Flow GC causes Orphaned Queues and Request Starvation
**What happened**:

Under bursty traffic conditions with Flow Control enabled, requests may be enqueued and subsequently orphaned. These requests are never successfully dispatched and eventually time out with a TTL expiry or context cancellation error.

Upon investigation, the `managedQueue` instances for these flows may be removed from the Shard's `priorityBands` map while requests are still pending inside them. This occurs because the FlowRegistry's "garbage collector" relies on a `leaseCount` that only tracks the duration of the *distribution phase* (the `WithConnection` call on the enqueue path), not the full request lifecycle. Once the distribution phase finishes, the lease count drops to zero. If the queue time exceeds `FlowGCTimeout` with no new enqueues (traffic is idle), the GC deletes the flow state, effectively "orphaning" the queue and making it invisible to the processor's dispatch loop.

**What you expected to happen**:

A Flow (and its associated queues on the shards) must not be Garbage Collected as long as there is at least one active request associated with it, regardless of whether that request is in the distribution phase or queueing.

**Anything else we need to know?**:

The current `FlowRegistry` GC logic uses a `sync.RWMutex` (`gcLock`) and an atomic `leaseCount`. The `leaseCount` is only incremented during the execution of the closure passed to `WithConnection`. Currently, the controller only wraps the `tryDistribution` logic in this closure.

**Environment**:

- Inference extension version: `main` (Experimental Flow Control layer enabled)

### PR DESCRIPTION
**Pull request by LukeAVanDrie**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

This PR fixes a race condition (Issue #1982) where the Flow Registry Garbage Collector could delete a Flow while it still had active requests waiting in a queue.

**The Bug**

Previously, `EnqueueAndWait` only acquired a Registry lease during the *distribution phase* (selecting a shard). Once the request was submitted to a shard's queue, the lease was released. In scenarios like "Scale from Zero," where requests sit in queues for longer than `FlowGCTimeout` without new incoming traffic, the Registry would see the flow as "Idle" (0 leases) and delete it. This orphaned the queues, causing requests to time out silently.

**The Fix**

We now extend the scope of `WithConnection` to cover the entire request lifecycle, from distribution until finalization (dispatch or timeout).
*   The flow remains "pinned" in memory as long as at least one request is active or queued.
*   The GC will correctly skip these flows during its sweep phase.

**Safety Note**
This change is only safe because of **PR #2127** (Optimistic Concurrency).
*   **Old Behavior (Mutex):** Holding a lease for minutes would have blocked the GC's Write Lock, which would have blocked all subsequent Read Locks, causing a total DoS on the system.
*   **New Behavior (Atomic):** We can hold the lease indefinitely. The GC simply sees `leaseCount > 0` via an atomic load and skips the flow without blocking.

**Which issue(s) this PR fixes**:
Fixes #1982

_Reviewer Notes:_

*   This PR must not be merged until **PR #2127** is merged.
*   **Interface Change:** Added `FlowKey()` to the `ActiveFlowConnection` contract. While not strictly necessary, this allows us to pass just the connection object down the stack, enforcing encapsulation.
*   **Testing:** Added `Regression_LeaseHeldDuringQueueing` to `controller_test.go`, which uses channels to deterministically prove the lease is not released while the processor is blocked.

**Does this PR introduce a user-facing change?**:

```release-note
Fixed a bug where flows could be garbage collected while requests were still queued during long wait times with no new traffic (e.g., scale-from-zero).
```

/hold
Waiting for PR #2127

### CODE REVIEW

File: pkg/epp/flowcontrol/controller/controller.go
Comment (LukeAVanDrie) [inline pkg/epp/flowcontrol/controller/controller.go:1]: The diff for `EnqueueAndWait` looks massive, but this is mostly due to indentation changes. I wrapped the existing distribution loop inside the `WithConnection` closure to extend the lease scope. Would recommend reviewing this with "Hide Whitespace" enabled.

**Comment by LukeAVanDrie** [comment]
@ahg-g These test will probably fail (deadlock) until #2127 is merged. That's expected as #2127 is a prerequisite (just with no conflicting code overlap).

**Comment by LukeAVanDrie** [comment]
> @ahg-g These test will probably fail (deadlock) until #2127 is merged. That's expected as #2127 is a prerequisite (just with no conflicting code overlap).

This is ready for review now that #2127 is merged.

File: pkg/epp/flowcontrol/controller/controller.go [hunk 1]
```diff
@@ -227,54 +227,74 @@ func (fc *FlowController) EnqueueAndWait(
...
 
-	// 2. Enter the distribution loop to find a home for the request.
-	// This loop is responsible for retrying on ErrShardDraining.
-	for {
-		select { // Non-blocking check on controller lifecycle.
-		case <-fc.parentCtx.Done():
-			return types.QueueOutcomeRejectedOther, fmt.Errorf("%w: %w", types.ErrRejected, types.ErrFlowControllerNotRunning)
-		default:
-		}
+	var finalOutcome types.QueueOutcome
```
Comment (ahg-g) [inline pkg/epp/flowcontrol/controller/controller.go:230]: Should we initialize this?

Comment (LukeAVanDrie) [reply pkg/epp/flowcontrol/controller/controller.go:230]: It initializes by default (it's an iota) to the semantically correct value, so this should be safe.

```
// QueueOutcome represents the high-level final state of a request's lifecycle within the `controller.FlowController`.
//
// It is returned by `FlowController.EnqueueAndWait()` along with a corresponding error. This enum is designed to be a
// low-cardinality label ideal for metrics, while the error provides fine-grained details for non-dispatched outcomes.
type QueueOutcome int

const (
	// QueueOutcomeNotYetFinalized indicates the request has not yet been finalized by the `controller.FlowController`.
	// This is an internal default value and should never be returned by `FlowController.EnqueueAndWait()`.
	QueueOutcomeNotYetFinalized QueueOutcome = iota
	...
)
...
```
