### PR TITLE
fix: log warning when pod ports don't match InferencePool targetPorts

### LINKED ISSUE #2562: EPP silently drops pods when container ports don't match InferencePool targetPorts
**What happened**:

When a pod matches an InferencePool's label selector but none of its container ports intersect with the pool's `targetPorts`, the pod is silently ignored no endpoint is created in the datastore, no warning is logged. The pod appears healthy (`Running`, labels match) but never receives traffic.

In `PodUpdateOrAddIfNotExist`[1], endpoints are only created for ports in `pool.TargetPorts`:

If no ports match, `pods` is empty and nothing is stored. No log is emitted.

**What you expected to happen**:

To assist in debugging EPP should consider logging a warning when a pod matching the pool's label selector produces zero active endpoints.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an InferencePool with `targetPorts: [8000]`
2. Deploy a pod that matches the pool's label selector but listens on a different port  in my example 8300
3. Observe that the pod is running and labels match, but EPP never routes traffic to it
4. No warning appears in EPP logs

This scenario arises in practice when using `hostNetwork: true` for RDMA prefill and decode pods share the host network namespace, forcing a port remap to avoid conflicts. If `targetPorts` isn't updated to match, the remapped pod is silently dropped. See llm-d/llm-d#632 [2]

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`): k3s v1.32
- Inference extension version (use `git describe --tags --dirty --always`): v1.3.1
- Cloud provider or hardware configuration: Bare metal, 2-node k3s, Mellanox ConnectX-4 (RoCE v2)
- Install tools: Helm
- Others: hostNetwork required for RDMA device access

[1] https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/ec45a9df7377986733d10cc68c7d6f5e244a87b7/pkg/epp/datastore/datastore.go#L266
[2] https://github.com/llm-d/llm-d/issues/632

### PR DESCRIPTION
**Pull request by hexfusion**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Adds a warning log when a pod matches an InferencePool's label selector but none of its container ports intersect with the pool's `targetPorts`. Previously the pod was silently ignored with no diagnostic output.

Also threads `ctx` through `PodUpdateOrAddIfNotExist` to follow the controller-runtime `log.FromContext(ctx)` pattern consistently.

**Which issue(s) this PR fixes**:

Fixes #2562

**Does this PR introduce a user-facing change?**:

```release-note
Log warning when pod matches InferencePool label selector but has no matching targetPorts
```

### CODE REVIEW

File: pkg/epp/datastore/datastore.go [hunk 1]
```diff
@@ -320,6 +320,13 @@ func (ds *datastore) podUpdateOrAddIfNotExist(pod *corev1.Pod, pool *datalayer.E
 			})
 	}
 
+	if len(pods) == 0 {
```
Comment (elevran) [inline pkg/epp/datastore/datastore.go:323]: Q: can be logged L306 (in `if !activePorts.Has(port) { ... }`)?

File: pkg/epp/metrics/collectors/inference_pool_test.go [hunk 2]
```diff
@@ -97,7 +97,7 @@ func TestMetricsCollected(t *testing.T) {
 			Build()
 
 		_ = ds.PoolSet(context.Background(), fakeClient, poolutil.InferencePoolToEndpointPool(inferencePool))
-		_ = ds.PodUpdateOrAddIfNotExist(pod1)
+		_ = ds.PodUpdateOrAddIfNotExist(context.Background(), pod1)
```
Comment (elevran) [inline pkg/epp/metrics/collectors/inference_pool_test.go:100]: Q: other test used `t.Context()`, any preferrence to that vs `contex.Background()`?

File: pkg/epp/requestcontrol/director_test.go [hunk 3]
```diff
@@ -786,7 +786,7 @@ func TestGetRandomEndpoint(t *testing.T) {
 					t.Errorf("unexpected error setting pool: %s", err)
 				}
 				for _, pod := range test.storePods {
-					ds.PodUpdateOrAddIfNotExist(pod)
+					ds.PodUpdateOrAddIfNotExist(context.Background(), pod)
```
Comment (elevran) [inline pkg/epp/requestcontrol/director_test.go:789]: ditto: `t.Context()`?

File: pkg/epp/metrics/collectors/inference_pool_test.go (hunk 2 above)
Comment (hexfusion) [reply pkg/epp/metrics/collectors/inference_pool_test.go:100]: just following the style from the line above it, and what I saw in general seems to be a mixed usage. i do not have strong feeling as long as its serving same purpose. would you advise adjusting all instances?

File: pkg/epp/datastore/datastore.go (hunk 1 above)
Comment (hexfusion) [reply pkg/epp/datastore/datastore.go:323]: logging per port felt a bit noisy which is why I went with a single log line isolating the condition "pod matched selector but no endpoints". i did drop the helper function as the user knows their pods ports to simplify this further.

File: pkg/epp/metrics/collectors/inference_pool_test.go (hunk 2 above)
Comment (elevran) [reply pkg/epp/metrics/collectors/inference_pool_test.go:100]: I see. Ultimately we would want consistency. I don't feel strongly enough to do it in this PR.
Will let others weigh in.

Comment (hexfusion) [reply pkg/epp/metrics/collectors/inference_pool_test.go:100]: no problem adjusting all tests to ensure consistency if we have consensus

**Comment by nirrozenbaum** [comment]
/approve

no need to block the PR on context consistency across tests.
overall it's always good to be consistent across the code in case you want to handle in a follow up 🙏 .
