### PR TITLE
fix: harden header sanitization and handling logic

### LINKED ISSUE #1624: Bug: Brittle header parsing leads to streaming failures and lost trace IDs
**What happened**:

Multiple header parsing locations in the codebase exclusively check the `RawValue` field of an Envoy `HeaderValue` message, completely ignoring the `Value` field. This makes header detection brittle and dependent on how a client or proxy populates the protobuf message. This single root cause created three distinct bugs:

1.  **Streaming Detection Failure:** The logic to detect `content-type: text/event-stream` in `pkg/epp/handlers/server.go` failed because it only checked `RawValue`.
2.  **Trace ID Loss:** The `ExtractHeaderValue` utility function in `pkg/epp/util/request/headers.go` also only checked `RawValue`, causing it to miss the `x-request-id` header.
3.  **Inconsistent Request ID Handling:** When a request arrived without an `x-request-id`, the processor would generate a new one but failed to consistently apply it back to the request context headers for downstream consumers.

**What you expected to happen**:

All header parsing logic should be robust and check for a header's value in both the `Value` and `RawValue` fields.  Any newly generated request IDs should be consistently available to all downstream logic.

**How to reproduce it (as minimally and precisely as possible)**:
1.  Send a gRPC `ProcessingRequest` to the external processor.
2.  In a `HeaderValue` message, set the desired value in the `Value` (string) field, not the `RawValue` (bytes) field.
3.  Observe that the processor fails to read the header correctly.

**Anything else we need to know?**:

_Root Cause Analysis:_

The Envoy `HeaderValue` protobuf message has two distinct fields for the value: `string value` and `bytes raw_value`. Both are valid parts of the API schema. The code made a faulty assumption that `RawValue` would always be the populated field, failing to check `Value` as a fallback.

_Production Risk / Impact:_

The production risk is **high**.

- **Streaming Failure:** If a client sends the `content-type: text/event-stream` header using the `Value` field, the gateway will fail to recognize the streaming response. It will attempt to buffer the entire response in memory, leading to high latency and excessive memory consumption, and potential OOM kills under load.
- **Observability Failure:** If the `x-request-id` header is sent using the `Value` field, the gateway will drop it and generate a new trace ID. This breaks the distributed trace, making it impossible to correlate requests across services and severely hindering debugging.

**Environment**:

- Discovered during hermetic integration testing refactoring.

### PR DESCRIPTION
**Pull request by LukeAVanDrie**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR hardens the HTTP header handling logic within the extension to ensure strict ownership of protocol and system metadata headers.

Previously, the header generation logic in `generateHeaders` (Request) and `generateResponseHeaders` (Response) acted as a transparent passthrough, appending user-supplied headers to the outgoing message.

**Changes:**
*   Strict Blocklist: Introduces `requtil.IsSystemOwnedHeader` to define a specific set of headers (Protocol, Routing, and Control) that must be managed exclusively by the extension.
*   Sanitization: Updates the header generation loops to silently drop any external values for these keys.

**Reasoning:**
These changes are necessary to prevent ambiguity in downstream proxies (Envoy) and backends. For example, internal routing headers should not be influenceable by external input.

**Which issue(s) this PR fixes**:
Fixes #1624

**Does this PR introduce a user-facing change?**:
```release-note
Harden header handling logic to enforce strict ownership of system and protocol headers, preventing potential ambiguity in backend routing and response processing.
```

### CODE REVIEW

File: pkg/epp/util/request/headers.go [hunk 1]
```diff
@@ -21,12 +21,41 @@ import (
...
 )
 
 const (
 	RequestIdHeaderKey = "x-request-id"
 )
 
+var (
+	// InputControlHeaders are sent by the Gateway/User to control EPP behavior.
+	// We must extract these, then strip them so they don't leak to the backend.
+	InputControlHeaders = map[string]bool{
```
Comment (nirrozenbaum) [inline pkg/epp/util/request/headers.go:34]: nit: there’s no meaning for the “true” here, and this map acts as a hash set. 
could be nice to use “set” from k8s utils instead of this map, and use the set.Has function (it’s backed by a map to struct{}).

it reads clearer IMO. 
(if you want to push in a follow up)

Comment (nirrozenbaum) [reply pkg/epp/util/request/headers.go:34]: example here:
https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/5ec1fa1d9a7ecc83e0ceee57c2d1abc656aa2716/pkg/epp/config/loader/configloader.go#L122

Comment (LukeAVanDrie) [reply pkg/epp/util/request/headers.go:34]: I considered this but figured `map[string]bool` or `map[string]struct{}` was idiomatic enough. The set utility reads nicer though, especially now that we have generics. Will send out a small followup!
