### PR TITLE
fix(datastore): remove orphaned rank endpoints when targetPorts changes

### LINKED ISSUE #2306: Stale rank endpoints remain after targetPorts update
**What happened:**

When InferencePool.spec.targetPorts is updated (e.g., shrinking from [8000, 8001, ..., 8007] to [8000]), the old rank endpoints remain in the datastore. The scheduler continues to route requests to these stale endpoints with incorrect ports.

For example, after updating targetPorts to [8000], a prefill pod that only listens on port 8000 was still being selected with port 8001 (from the orphaned rank-1 entry):

Root cause: In datastore.go PoolSet(), podResyncAll() is only triggered when the Selector changes, not when TargetPorts change. Additionally, PodUpdateOrAddIfNotExist() creates/updates endpoints for current targetPorts but never deletes endpoints from previously removed ranks.

**What you expected to happen:**

When targetPorts is updated from 8 ports to 1, all rank-1 through rank-7 endpoints should be removed from the datastore. Only rank-0 should remain, and the scheduler should only route to valid ports.

**How to reproduce it (as minimally and precisely as possible):**

Create an InferencePool with multiple targetPorts:

```yaml
spec:
  targetPorts:
    - number: 8000
    - number: 8001
```
Wait for pods to reconcile, each pod gets 2 endpoints: pod-rank-0 (port 8000) and pod-rank-1 (port 8001)
Update the InferencePool to a single targetPort:

```yaml
spec:
  targetPorts:
    - number: 8000
```
Send inference requests scheduler may still select the orphaned rank-1 endpoint with port 8001

**Anything else we need to know?:**

The issue is in two places in `pkg/epp/datastore/datastore.go`:

PoolSet() : only checks selector changes, not targetPorts changes:

```go
if oldEndpointPool == nil || !labels.Equals(oldEndpointPool.Selector, endpointPool.Selector) {
    // podResyncAll() only called here
}
```
PodUpdateOrAddIfNotExist() : creates new rank entries based on current targetPorts but does not delete old rank entries that no longer exist.

A possible fix would be to also trigger podResyncAll() when targetPorts change, or to have PodUpdateOrAddIfNotExist() clean up rank entries beyond the current len(ds.pool.TargetPorts).

Workaround: Restart the EPP process after changing targetPorts.

**Environment:**

Kubernetes version: v1.32.5
Inference extension version: 74b7a04b

### PR DESCRIPTION
**Pull request by bongwoobak**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

When `InferencePool.spec.targetPorts` is updated (e.g., shrinking from multiple ports to fewer ports), the old rank endpoints were not being removed from the datastore. This caused the scheduler to route requests to non-existent ports.

This PR fixes the issue by:
1. Triggering `podResyncAll()` when `targetPorts` changes, not just when `selector` changes
2. Tracking active endpoints by their full name (including rank suffix) in `podResyncAll()` to properly identify and remove orphaned rank endpoints
3. Adding `TestTargetPortsChange`

**Which issue(s) this PR fixes**:

Fixes #2306

**Does this PR introduce a user-facing change?**:

```release-note
Fixed a bug where orphaned rank endpoints remained in the datastore when InferencePool targetPorts were updated, causing requests to be routed to non-existent ports.
```

### CODE REVIEW

File: pkg/epp/datastore/datastore.go [hunk 1]
```diff
@@ -328,26 +334,36 @@ func (ds *datastore) podResyncAll(ctx context.Context, reader client.Reader) err
...
 		if !podutil.IsPodReady(&pod) {
 			continue
 		}
 		namespacedName := types.NamespacedName{Name: pod.Name, Namespace: pod.Namespace}
-		activePods.Insert(pod.Name)
+		// Calculate expected endpoint names based on current targetPorts.
+		for idx := range ds.pool.TargetPorts {
+			activeEndpoints.Insert(types.NamespacedName{
+				Name:      pod.Name + "-rank-" + strconv.Itoa(idx),
+				Namespace: pod.Namespace,
```
Comment (ahg-g) [inline pkg/epp/datastore/datastore.go]: This needs to match with the way we form the namespacedName in `PodUpdateOrAddIfNotExist`; can  we pls create a function to encapsulate this? `CreateEndpointNamespacedName(pod v1.Pod, idx int)`

File: pkg/epp/datastore/datastore.go [hunk 2]
```diff
@@ -44,6 +45,15 @@ var (
...
 
+// CreateEndpointNamespacedName creates a namespaced name for an endpoint based on pod and rank index.
+// This ensures consistent naming between PodUpdateOrAddIfNotExist and podResyncAll.
+func CreateEndpointNamespacedName(pod *corev1.Pod, idx int) types.NamespacedName {
+	return types.NamespacedName{
+		Name:      pod.Name + "-rank-" + strconv.Itoa(idx),
+		Namespace: pod.Namespace,
+	}
+}
+
```
Comment (ahg-g) [inline pkg/epp/datastore/datastore.go]: nit, please make it private and move it to the end of the file so that the Datastore interface stays at the top (since this whole pkg is about the Datastore)
