### PR TITLE
fix(release): update quickstart guide version automatically

### LINKED ISSUE #1784: Release script should update the latest version in quickstart guide (latest tab)
current release script doesn't update the version in quickstart, which result in needing to update that manually.
we should automate when possible.

### PR DESCRIPTION
**Pull request by AvineshTripathi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1784

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: hack/release-quickstart.sh [hunk 1]
```diff
@@ -135,8 +135,8 @@ sed -i.bak -E "s|us-central1-docker\.pkg\.dev/k8s-staging-images|registry.k8s.io
 
 # Update IGW_CHART_VERSION in quickstart guide to match the current release tag
 GUIDES_INDEX="site-src/guides/index.md"
-sed -i.bak -E "s/export IGW_CHART_VERSION=v[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?/export IGW_CHART_VERSION=${RELEASE_TAG}/g" "$GUIDES_INDEX"
-
+OLD_VERSION=$(grep -oE 'export IGW_CHART_VERSION=v[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?' "$GUIDES_INDEX" | head -n1 | cut -d'=' -f2)
+sed -i.bak -E "s/${OLD_VERSION}/${RELEASE_TAG}/g" "$GUIDES_INDEX"
```
Comment (nirrozenbaum) [inline hack/release-quickstart.sh:139]: I think this change doesn't cover all the places where the version appears.

for example - the `kubectl apply` commands that deploy a yaml.

Comment (AvineshTripathi) [reply hack/release-quickstart.sh:139]: Hey @nirrozenbaum, got it are you referring to version mentions in other places (like kubectl commands in other files)? If you’ve spotted a specific case where it misses, can you point me to it?

I tested this locally with a quick hack:

```
GUIDES_INDEX="../site-src/guides/index.md"
OLD_VERSION=$(grep -oE 'export IGW_CHART_VERSION=v[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?' "$GUIDES_INDEX" | head -n1 | cut -d'=' -f2)
echo $OLD_VERSION
sed -i.bak -E "s/${OLD_VERSION}/${RELEASE_TAG}/g" "$GUIDES_INDEX"
```

It correctly updated the .md file, so just want to confirm if I’m missing another place or case where this wouldn’t work?

Comment (nirrozenbaum) [reply hack/release-quickstart.sh:139]: yes I was talking about kubectl commands. but I just verified that your fix is working as expected.
sorry, my mistake.

Thanks!

/ok-to-test
/lgtm
/approve
