### PR TITLE
fix(prefixcache): hash trailing bytes to prevent multimodal URL hotspotting

### LINKED ISSUE #1980: Multimodal support in IGW (initial triage)
Presently, IGW doesn't support multimodal completely. The following are the gaps:

* Support for video/audio data formats
* Support for prefix caching. The present strategy may not work based on discussion in https://www.youtube.com/watch?v=-WqJ8PbnFg8 . This will be addressed in issue #2172 

For further investigation, refer: https://docs.google.com/document/d/1YKx31zmF-mMGgb41InQfNmaOIVlAElsUXHIgHfQe_68/edit?tab=t.0

### LINKED ISSUE #2172: MultiModal approximate prefix cache aware
* we can simply prepend image/video info before prompt [hash](https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/812efb21ee069e16617a78d7d39e7822d736f6cf/pkg/epp/scheduling/framework/plugins/multi/prefix/plugin.go#L231)
* or hash URL(video/image) and match it

### PR DESCRIPTION
**Pull request by rahulgurnani**
**What this PR does / why we need it**:

This change ensures that video/image urls with same prefix don't go to same pod in cases when the video/image URLs share the same prefix. This can happen commonly since often images/videos may reside in the same bucket

**Current behavior**

Imagine that a prompt shares same prefix blocks across multiple requests. 

Imagine 2 image urls like:
```
https://www.imagewebsite.com/image1.jpg
https://www.imagewebsite.com/image2.jpg
```
these 2 share the same prefix until the last few characters and are suspectible to go to the same pod. This is because presently we ignore the last block in prefix hashing. This causes hotspotting as observed in local bechmarking as well when requests get dropped due to model server crashing.

**Testing**
Tested the change in unit tests to reproduce the exact case. The unit test TestPrefixPluginChatCompletionsMultimodalDifferentUrlSomeMatch and TestPrefixPluginChatCompletionsMultimodalSameUrlFullMatch verify these changes.

Furthermore, ran a benchmark which confirms hotspotting.

**What type of PR is this?**

/kind feature

**Which issue(s) this PR fixes**:

Fixes #1980

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by rahulgurnani** [comment]
Sending this out based on offline discussions with @capri-xiyue

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go [hunk 1]
```diff
@@ -108,9 +123,27 @@ func getUserInputBytes(request *scheduling.LLMRequest) ([]byte, error) {
 		}
 		combined = append(combined, map[string]interface{}{"input": request.Body.Responses.Input})
 		return json.Marshal(combined)
-
 	case request.Body.ChatCompletions != nil:
-		return json.Marshal(request.Body.ChatCompletions.Messages)
+		var combined []any
```
Comment (capri-xiyue) [inline pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: If you take a look at the logic in main branch, when it marshals the message, it will include the `role`. But here, you ignore it. I'm not sure whether it will bring any side effects

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go [hunk 2]
```diff
@@ -108,9 +123,27 @@ func getUserInputBytes(request *scheduling.LLMRequest) ([]byte, error) {
 		}
 		combined = append(combined, map[string]interface{}{"input": request.Body.Responses.Input})
 		return json.Marshal(combined)
-
 	case request.Body.ChatCompletions != nil:
```
Comment (capri-xiyue) [inline pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go:122]: Besides chat completion, conversation api also support multimodal

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go [hunk 3]
```diff
@@ -108,9 +123,27 @@ func getUserInputBytes(request *scheduling.LLMRequest) ([]byte, error) {
...
-		return json.Marshal(request.Body.ChatCompletions.Messages)
+		var combined []any
+		for _, msg := range request.Body.ChatCompletions.Messages {
```
Comment (capri-xiyue) [inline pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: Here, you iterate through the messages and hash it， I'm wondering whether it will be better to deep copy the Messages and just try to hash the multimodal item. It's open for discussion.

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go (hunk 1 above)
Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: updated to add role. Also updated the code to a make it more modular.

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go (hunk 2 above)
Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go:122]: I agree. We need to do it for responses API as well. Presently, the responses API requests are parsed to a struct like the way its done for chat completions. 
Ref: https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/pkg/epp/framework/interface/requesthandling/types.go#L221
Also, vllm bench doesn't support responses API with multimodal inputs presently. Thinking of addressing that in a separate change as it may require some manual script to do testing of that change. Added a TODO for now.

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go (hunk 3 above)
Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: Go doesn't have a built in library for deep copy. We would need to use a third party library which have some overhead in terms usage. I don't think the API is changing going forward, like since chat completions API has been here for a while, it seems there is going to be additions to the existing fields in chat completions api. Would let others chime in as well cc @liu-cong

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go [hunk 4]
```diff
@@ -108,9 +176,13 @@ func getUserInputBytes(request *scheduling.InferenceRequest) ([]byte, error) {
 		}
 		combined = append(combined, map[string]interface{}{"input": request.Body.Responses.Input})
 		return json.Marshal(combined)
-
+		
 	case request.Body.ChatCompletions != nil:
-		return json.Marshal(request.Body.ChatCompletions.Messages)
+		res, err := parseChatCompletions(request.Body.ChatCompletions.Messages)
```
Comment (zetxqx) [inline pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: Instead of completely reconstruct the json format and marshal it on LINE#185. Do you think it's more intuitive we just replace the url to a hashed value in the JSON payload, and do the json.Marshal again? Since it's approximate, I feel the current method is a little hard to understand and is not very easy to explain.


E.g.:

```json
"messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "What is described in this image?"
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "https://example.com/path/to/your/image.jpg",
          }
        }
      ]
    }
  ],
```
to 

```json
"messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "What is described in this image?"
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "hashed_value",
          }
        }
      ]
    }
  ],
```

Then json.Marshal the whole json struct.

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go [hunk 5]
```diff
@@ -93,12 +97,76 @@ func toBytes(i blockHash) []byte {
 	return bytes
 }
 
+func hashMultimodalBlock(block requesthandling.ContentBlock) (string, error) {
+	b, err := json.Marshal(block)
+	if err != nil {
+		return "", err
+	}
+	hash := blake3.Sum256(b)
```
Comment (zetxqx) [inline pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: How about reuse "github.com/cespare/xxhash/v2" hash function?

From gemini

```
xxHash: It is one of the fastest hash algorithms in existence. It is often limited only by the memory bandwidth of the RAM. It is significantly faster than BLAKE3 when security is not a concern.

BLAKE3: While it is incredibly fast for a cryptographic hash (much faster than SHA-256 or SHA-3), it still involves more complex mathematical operations than xxHash. It is highly parallelizable, meaning it gets much faster as the data size increases and more CPU cores are used.
```

Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: vLLM uses blake3 by default for multimodal so keeping it same for consistency: https://docs.vllm.ai/en/stable/api/vllm/multimodal/hasher/
Also, in blake3 chance of collisions is practically zero (~2^128).  
I understand the collision probability for xxhash is still acceptable, its about 1 in a billion. 
Updated the code to use xxhash for now, since we are already using it in this file.

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go (hunk 3 above)
Comment (capri-xiyue) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: you can json marshal and unmarshal to deep copy it， see example https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/cca49cd3f1f1bd385af8ad2c8eaaeacf0543b91a/pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go#L153

Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: Just saw your comment, I ended up creating messages in-memory while addressing https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/2823#discussion_r3090075621

Hope that addresses it. Thanks!

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go (hunk 4 above)
Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: Sure, updated. thanks!

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go (hunk 3 above)
Comment (capri-xiyue) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: I feel clone a new copy using marshal and unmarshal is safer.  For example later when messages become more compelx and add more fields, you don't need to copy each field.

Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: I thought about it too, 2 reasons why I think its not an issue:

1. These messages are for requests that follow chat completions api which is now stable and in mostly in a support mode. Responses API is what's undergoing change. I don't think we expect changes in the chat completions API.
2. In cases when we end up changing message struct, the author can automatically look for other occurrences of message struct and can update it here

Also, I think this is more readable.

Thanks!

**Comment by rahulgurnani** [comment]
Based on offline discussion with @liu-cong and @capri-xiyue , scoping this change to ensuring the last block is taken so we don't send different urls that share prefix to same pod. Update the PR accordingly. cc @ahg-g

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go [hunk 6]
```diff
@@ -28,6 +28,12 @@ import (
 	"sigs.k8s.io/gateway-api-inference-extension/pkg/epp/framework/interface/scheduling"
 )
 
+const (
```
Comment (capri-xiyue) [inline pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: Besides test, is there anywhere else you use this const? If it is just for testing, move it to test file

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go [hunk 7]
```diff
@@ -93,12 +109,14 @@ func toBytes(i blockHash) []byte {
 	return bytes
 }
 
+
```
Comment (capri-xiyue) [inline pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: remove unneeded change

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go [hunk 8]
```diff
@@ -0,0 +1,218 @@
...
+
+import (
+	"encoding/json"
+	"testing"
+
+	"sigs.k8s.io/gateway-api-inference-extension/pkg/epp/framework/interface/requesthandling"
+	"sigs.k8s.io/gateway-api-inference-extension/pkg/epp/framework/interface/scheduling"
+)
+
+const userRole = "user"
```
Comment (capri-xiyue) [inline pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go]: nit: write all const in a block

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go [hunk 9]
```diff
@@ -0,0 +1,218 @@
...
+
+const longURL = "https://storage.googleapis.com/averylargesizednameofabuckettostoreimages/sample52.jpg"
+
+func TestGetUserInputBytes_ChatCompletions(t *testing.T) {
+	tests := []struct {
+		name    string
+		request *scheduling.InferenceRequest
+		verify  func(t *testing.T, got []byte)
+		wantErr bool
```
Comment (capri-xiyue) [inline pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go]: It maybe more robust to also UT the error message（nice to have, depends on you)

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go [hunk 10]
```diff
@@ -0,0 +1,218 @@
...
+			},
+			verify: func(t *testing.T, got []byte) {
+				var messages []requesthandling.Message
+				if err := json.Unmarshal(got, &messages); err != nil {
+					t.Fatalf("Failed to unmarshal: %v", err)
+				}
+				if len(messages) != 1 {
+					t.Fatalf("Expected 1 message, got %d", len(messages))
+				}
+				if messages[0].Role != userRole {
```
Comment (capri-xiyue) [inline pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go]: It will be better if you can make everything you want to verify as a expected output, currently you write it as a verify function, I think the readablity is low.

For example, you can have  `want  []requesthandling.Message`  in test cases and then compare it

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go (hunk 6 above)
Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: I was using it earlier in this file. Moved it to test. Thanks!

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go (hunk 8 above)
Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go]: done, thanks!

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go (hunk 7 above)
Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing.go]: updated, thanks!

**Review by liu-cong — APPROVED** [review]
/lgtm

/approve

Please update the PR title to something like "Consider last partial block in prefix matching" to be more precise

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go (hunk 9 above)
Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go]: outdated, the test is no longer needed. thanks!

File: pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go (hunk 10 above)
Comment (rahulgurnani) [reply pkg/epp/framework/plugins/requestcontrol/dataproducer/approximateprefix/hashing_test.go]: outdated. thanks!

**Comment by rahulgurnani** [comment]
> /lgtm
> 
> /approve
> 
> Please update the PR title to something like "Consider last partial block in prefix matching" to be more precise

thanks! updated the PR title
