### PR TITLE
test: fix flaky garbage collection test

### LINKED ISSUE #1871: test flake in flow control - GarbageCollection
flaky test in flow control garbage collection. test failed in a PR that is not touching EPP at all (changes to BBR).
log here:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_gateway-api-inference-extension/1867/pull-gateway-api-inference-extension-test-unit-main/1990346538060091392

cc: @LukeAVanDrie

### PR DESCRIPTION
**Pull request by LukeAVanDrie**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
This PR fixes a flaky unit test in the Flow Control registry (`TestFlowRegistry_GarbageCollection`).

The test was failing intermittently (~0.7% rate) because of a race condition between the test logic and the background Garbage Collector loop started by the test harness.

**The Race:**
1. The test calls `h.fakeClock.Step()` to advance time for a manual sweep verification.
2. This inadvertently wakes up the background GC loop.
3. If the background GC acquires the flow lock before the test does, it sees the flow is "idle" and deletes it immediately.
4. The test then tries to mark the flow as "active" to verify the sweep abortion logic, but fails because the flow no longer exists.

**The Fix:**
The test now acquires the flow's `gcLock` before calling `Step()`. This ensures that when the background GC wakes up, it immediately blocks on the lock, allowing the test to finish setting up the state (marking the flow as active) without interference.

**Which issue(s) this PR fixes**:
Fixes #1871

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by LukeAVanDrie** [comment]
e2e test flake is unrelated to my change; will file a flake report in the morning

/retest

File: pkg/epp/flowcontrol/registry/registry_test.go [hunk 1]
```diff
@@ -367,37 +367,41 @@ func TestFlowRegistry_GarbageCollection(t *testing.T) {
...
 		val, ok := h.fr.flowStates.Load(key)
 		require.True(t, ok, "Test setup: flow state must exist")
 		state := val.(*flowState)
 
-		// Lock the flow's `gcLock` to pause the GC.
+		// Acquire the lock before stepping the clock.
+		// This ensures the Background GC (which wakes up on Step) is blocked and cannot touch our flow until we release
+		// this lock.
 		state.gcLock.Lock()
 		defer state.gcLock.Unlock()
```
Comment (shmuelk) [inline pkg/epp/flowcontrol/registry/registry_test.go:379]: Here you use `defer` to unlock the gcLock, yet in line 399 below, you explicitly unlock the gcLock.

That seems to be a bug here.

Comment (LukeAVanDrie) [reply pkg/epp/flowcontrol/registry/registry_test.go:379]: It works, but it is a code smell.

This isn't included in the diff view, but look at the last line of this test case:

```
...
  h.assertFlowExists(key, "Flow should not be collected because it became active before the sweep")
  state.gcLock.Lock() // Re-lock for the deferred unlock.
})
```

It's actually a bit brittle. If the test were to fail (e.g., t.Fatal) after the explicit unlock but before the final re-lock, the defer would trigger a double-unlock panic, masking the actual test failure.

E.g., in

```
// Wait for the manual sweep to complete.
select {
case <-sweepDone:
  // Success
case <-time.After(time.Second):
  t.Fatal("verifyAndSweepFlows deadlocked or timed out")
}
```

Comment (LukeAVanDrie) [reply pkg/epp/flowcontrol/registry/registry_test.go:379]: This test is necessarily a bit brittle and white-box as it deterministically triggers a race condition. I can clean this test up a bit by removing the `defer` entirely. However, the consequence of this is that if the test panics or fails between the lock and unlock, the lock will be leaked. This is probably fine for a unit test. Especially because the code in the critical section is unlikely to fail.

Revised, it looks like this:
```
...
state.gcLock.Lock()

h.fakeClock.Step(h.config.FlowGCTimeout + time.Second)
candidates := []types.FlowKey{key}

sweepDone := make(chan struct{})
go func() {
  defer close(sweepDone)
  h.fr.verifyAndSweepFlows(candidates)
}()

state.leaseCount.Add(1)
state.gcLock.Unlock()
...
```

Comment (LukeAVanDrie) [reply pkg/epp/flowcontrol/registry/registry_test.go:379]: Let me know your thoughts - I think the revised code above is slightly preferable and less confusing for future maintainers.
