### PR TITLE
Filter inference objectives based on inference pool group

### LINKED ISSUE #1275: EPP reconcile more InferenceModels than the InferenceModel related to the specified InferencePool
**What happened**:
EPP reconcile more InferenceModels than the InferenceModel related to the specified InferencePool

**What you expected to happen**:
EPP reconcile  InferenceModels related to the specified InferencePool

**How to reproduce it (as minimally and precisely as possible)**:
With scenario like this 

Image

However, when I check the EPP deployment which handles v1a2 InferencePool, the logs shows it also reconcile InferenceModel related to v1 InferencePool

**Anything else we need to know?**:
Looks like it is because of https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/pkg/epp/controller/inferencemodel_reconciler.go#L39.

Need to add additional `group` to differentiate between IP with same namespace and name but different group

**Environment**:
- Kubernetes version (use `kubectl version`):
- Inference extension version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by nicolexin**
fixed #1275 

Previously, EPP reconciles more InferenceModels than the InferenceModel related to the specified InferencePool. We check against the inference pool name and namespace, but not the group.

This PR added the check against inference pool group.

NOTE: Currently the poolRef.group defaults to "inference.networking.x-k8s.io" (see https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/apix/v1alpha2/inferenceobjective_types.go#L114), which is inconsistent with the default defined in EPP startup arg "--pool-group=inference.networking.k8s.io" in #1277.

### CODE REVIEW

**Comment by nicolexin** [comment]
cc @robscott

I noticed an inconsistency - 

In InferenceObjective CRD, the poolRef.group defaults to "inference.networking.**x-k8s**.io" (see https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/apix/v1alpha2/inferenceobjective_types.go#L114)

However, the default defined in EPP startup arg is "--pool-group=inference.networking.**k8s**.io" (if not specified). See https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1277.

Shall we change the InferenceObjective CRD default to "inference.networking.k8s.io"?

File: pkg/epp/controller/inferenceobjective_reconciler.go [hunk 1]
```diff
@@ -56,7 +56,7 @@ func (c *InferenceObjectiveReconciler) Reconcile(ctx context.Context, req ctrl.R
 		notFound = true
 	}
 
-	if notFound || !infObjective.DeletionTimestamp.IsZero() || infObjective.Spec.PoolRef.Name != v1alpha2.ObjectName(c.PoolGKNN.Name) {
+	if notFound || !infObjective.DeletionTimestamp.IsZero() || infObjective.Spec.PoolRef.Name != v1alpha2.ObjectName(c.PoolGKNN.Name) || infObjective.Spec.PoolRef.Group != v1alpha2.Group(c.PoolGKNN.Group) {
```
Comment (kfswain) [inline pkg/epp/controller/inferenceobjective_reconciler.go:57]: We should add this to the predicate also: https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/115aa8588fd0a4fb7847a7723bc8f9fad57f6b61/pkg/epp/controller/inferenceobjective_reconciler.go#L128

Comment (nicolexin) [reply pkg/epp/controller/inferenceobjective_reconciler.go:57]: Good catch, updated!

**Comment by robscott** [comment]
> In InferenceObjective CRD, the poolRef.group defaults to "inference.networking.**x-k8s**.io" (see [`main`/apix/v1alpha2/inferenceobjective_types.go#L114](https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/apix/v1alpha2/inferenceobjective_types.go#L114))
> 
> However, the default defined in EPP startup arg is "--pool-group=inference.networking.**k8s**.io" (if not specified). See #1277.
> 
> Shall we change the InferenceObjective CRD default to "inference.networking.k8s.io"?

Good catch, that would be great to fix, thanks @nicolexin!

**Comment by kfswain** [comment]
> > In InferenceObjective CRD, the poolRef.group defaults to "inference.networking.**x-k8s**.io" (see [`main`/apix/v1alpha2/inferenceobjective_types.go#L114](https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/apix/v1alpha2/inferenceobjective_types.go#L114))
> 
> > 
> 
> > However, the default defined in EPP startup arg is "--pool-group=inference.networking.**k8s**.io" (if not specified). See #1277.
> 
> > 
> 
> > Shall we change the InferenceObjective CRD default to "inference.networking.k8s.io"?
> 
> 
> 
> Good catch, that would be great to fix, thanks @nicolexin!

Cc'ing: @danehans @nirrozenbaum @LiorLieberman to weigh in also

**Comment by nirrozenbaum** [comment]
> > > In InferenceObjective CRD, the poolRef.group defaults to "inference.networking.**x-k8s**.io" (see [`main`/apix/v1alpha2/inferenceobjective_types.go#L114](https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/apix/v1alpha2/inferenceobjective_types.go#L114))
> > 
> > 
> > > 
> > 
> > 
> > > However, the default defined in EPP startup arg is "--pool-group=inference.networking.**k8s**.io" (if not specified). See #1277.
> > 
> > 
> > > 
> > 
> > 
> > > Shall we change the InferenceObjective CRD default to "inference.networking.k8s.io"?
> > 
> > 
> > Good catch, that would be great to fix, thanks @nicolexin!
> 
> Cc'ing: @danehans @nirrozenbaum @LiorLieberman to weigh in also

I'd keep the previous CRD version as default at least until the 3 leading gateway implementations have support in v1 CRD.
the main point I'm looking at is being able to upgrade from v0.5.1 to v1 with as less disruption as possible.
if we make the v1 CRD the default at this point where gateways still don't support it - we add noise to whoever is using GIE when they upgrade to the newest version.
the plan I would recommend is:
1. keep existing CRD version as default and add support of V1.
2. coordinate with our partners on gateways support of v1 including some time commitments. 
3. when the gateways are ready, we switch to v1 and keep v1alpha2 for additional month or so with a deprecation announcement (that it will be removed in next release).

this is also similar to how we did with other features, for example with the deprecation of decision tree filter in scheduling. we implemented an alternative, enabled it through a special EXPERIMENTAL env var but kept the existing default, when we felt ready we switched to the new mechanism and deprecated the previous one.

File: pkg/epp/controller/inferenceobjective_reconciler_test.go [hunk 2]
```diff
@@ -85,7 +85,13 @@ var (
...
 				CreationTimestamp(metav1.Unix(999, 0)).
 				PoolName(pool.Name).ObjRef()
-
+	infObjective1DiffGroup = utiltest.MakeInferenceObjective("model1").
+				Namespace(pool.Namespace).
+				ModelName("fake model1").
+				Criticality(v1alpha2.Standard).
+				CreationTimestamp(metav1.Unix(1000, 0)).
+				PoolName(pool.Name).
+				PoolGroup("diff-group").ObjRef()
```
Comment (capri-xiyue) [inline pkg/epp/controller/inferenceobjective_reconciler_test.go]: I'm wondering whether it's less confusing to use real pool group name such as ""inference.networking.x-k8s.io" and "inference.networking.x-k8s.io" instead of fake group name like "diff-group"

File: pkg/epp/controller/inferenceobjective_reconciler_test.go [hunk 3]
```diff
@@ -177,6 +183,17 @@ func TestInferenceObjectiveReconciler(t *testing.T) {
 			objective:          infObjective2,
 			wantObjectives:     []*v1alpha2.InferenceObjective{infObjective1, infObjective2},
 		},
+		{
+			name:               "Objective deleted due to group mismatch for the inference pool",
+			objectivessInStore: []*v1alpha2.InferenceObjective{infObjective1},
```
Comment (capri-xiyue) [inline pkg/epp/controller/inferenceobjective_reconciler_test.go:134]: Do we need to change the infObjective to have a specified poolgroup instead of default nil or ""

**Comment by capri-xiyue** [comment]
The unit-test failed because of NPE. Probably because the group of PoolRef is nil.

File: pkg/epp/controller/inferenceobjective_reconciler_test.go [hunk 4]
```diff
@@ -85,7 +85,13 @@ var (
 				Criticality(v1alpha2.Standard).
 				CreationTimestamp(metav1.Unix(999, 0)).
 				PoolName(pool.Name).ObjRef()
-
+	infObjective1DiffGroup = utiltest.MakeInferenceObjective("model1").
```
Comment (capri-xiyue) [inline pkg/epp/controller/inferenceobjective_reconciler_test.go]: Probably also need to change the above infObjective like `infObjective1`, infObjectiveNS2` and so on to `inference.networking.k8s.io`

File: pkg/epp/controller/inferenceobjective_reconciler_test.go (hunk 3 above)
Comment (nicolexin) [reply pkg/epp/controller/inferenceobjective_reconciler_test.go:134]: The default is actually "inference.networking.x-k8s.io" due to https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/apix/v1alpha2/inferenceobjective_types.go#L114. The NPE test failure is due to the InferenceObjective poolRef.group (v1alpha1) not matching the pool group (v1). As a result there is no matching inference pool for the objective, and all objectives gets deleted. This is the line that failed

I updated the testdata to use v1 as the poolRef.group and now all tests passed.

File: pkg/epp/controller/inferenceobjective_reconciler_test.go (hunk 2 above)
Comment (nicolexin) [reply pkg/epp/controller/inferenceobjective_reconciler_test.go]: Sure thing, I changed it to "inference.networking.x-k8s.io".

File: pkg/epp/controller/inferenceobjective_reconciler_test.go (hunk 4 above)
Comment (nicolexin) [reply pkg/epp/controller/inferenceobjective_reconciler_test.go]: I have made all of them explicit now :)
