### PR TITLE
fix: make port number become pointer

### LINKED ISSUE #1386: InferencePool: Finalize InferencePool.ExtensionRef.PortNumber
**What happened**:
https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/1366#discussion_r2271495694 changed  InferencePool.ExtensionRef.PortNumber to be non-pointer. However, based on https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#serialization-of-optionalrequired-fields, 0 is not allowed and this is optional and doesn’t have built in nil type, seems like we need to use pointer here.

In addition, 
reading the API spec (When unspecified, implementations SHOULD infer a default value of 9002 when the Kind is Service) 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Inference extension version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by capri-xiyue**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
InferencePool.ExtensionRef.PortNumber should be a pointer and KIA doesn't apply here as 0 usually means all ports. Should not use 0 to indicate it is user not set.

**Which issue(s) this PR fixes**:

Fixes #1386 

**Does this PR introduce a user-facing change?**:
None

```release-note

```

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @capri-xiyue!

/lgtm

**Comment by kfswain** [comment]
looks good, will stamp when CI is passing

File: api/v1/inferencepool_types.go [hunk 1]
```diff
@@ -123,7 +123,9 @@ type Extension struct {
 	// Service.
 	//
 	// +optional
-	PortNumber PortNumber `json:"portNumber,omitempty"`
+	//nolint:kubeapilinter
+	// ignore kubeapilinter here as we want to use pointer here as 0 usually means all ports.
```
Comment (robscott) [inline api/v1/inferencepool_types.go]: To avoid change to CRD + reference docs, recommend combining in one line:
```suggestion
	//nolint:kubeapilinter // ignore kubeapilinter here as we want to use pointer here as 0 usually means all ports.
```

Comment (capri-xiyue) [reply api/v1/inferencepool_types.go]: done

File: api/v1/inferencepool_types.go [hunk 2]
```diff
@@ -123,7 +123,8 @@ type Extension struct {
 	// Service.
 	//
 	// +optional
-	PortNumber PortNumber `json:"portNumber,omitempty"`
+	//nolint:kubeapilinter // ignore kubeapilinter here as we want to use pointer here as 0 usually means all ports.
```
Comment (JoelSpeed) [inline api/v1/inferencepool_types.go:126]: This is a suboptimal way of excluding KAL on this field. It's preferable to exclude a single error message via the golangci-lint config directly.

That way you'll be able to still benefit from other issues that KAL reports on this field, without disabling linting for the field altogether.

The config is something like:

```
exclude_rules:
- text: "PortNumber does not have a valid zero value and does not need to be a pointer"
  path: api/v1/inferencepool_types.go
```
