### PR TITLE
fix: adds ErrorNotFound Handling for InferenceModel Reconciler

### LINKED ISSUE #280: EPP Logs InferenceModel Not Found
**What happened**:

When the sample InferenceModel is deleted, EPP continues to log the following:

```
E0204 15:52:10.961380       1 controller.go:341] "Reconciler error" err="InferenceModel.inference.networking.x-k8s.io \"inferencemodel-sample\" not found" controller="inferencemodel" controllerGroup="inference.networking.x-k8s.io" controllerKind="InferenceModel" InferenceModel="default/inferencemodel-sample" namespace="default" name="inferencemodel-sample" reconcileID="f1700e95-b7d2-4fd0-b7c8-7b77d9c4671d"
```

**What you expected to happen**:

Not to receive continuous `NOT FOUND` log messages.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the POC readme and then delete the InferenceModel.

### PR DESCRIPTION
**Pull request by danehans**
- Updates InferenceModel reconciler to not return an error if the InferenceModel is not found.
- Updates InferenceModel reconciler to remove the InferenceModel from the datatstore if it's not found.
- Adds unit tests

Fixes #280

### CODE REVIEW

File: pkg/ext-proc/backend/inferencemodel_reconciler.go [hunk 1]
```diff
@@ -25,32 +26,37 @@ func (c *InferenceModelReconciler) Reconcile(ctx context.Context, req ctrl.Reque
 	if req.Namespace != c.PoolNamespacedName.Namespace {
 		return ctrl.Result{}, nil
 	}
-	klog.V(1).Infof("reconciling InferenceModel %v", req.NamespacedName)
-
-	service := &v1alpha1.InferenceModel{}
-	if err := c.Get(ctx, req.NamespacedName, service); err != nil {
-		klog.Error(err, "unable to get InferencePool")
+	klog.V(1).Infof("Reconciling InferenceModel %v", req.NamespacedName)
```
Comment (ahg-g) [inline pkg/ext-proc/backend/inferencemodel_reconciler.go:29]: use logging levels pls, DEFAULT in this case

File: pkg/ext-proc/backend/inferencemodel_reconciler.go [hunk 2]
```diff
@@ -25,32 +26,37 @@ func (c *InferenceModelReconciler) Reconcile(ctx context.Context, req ctrl.Reque
...
+
+	infModel := &v1alpha1.InferenceModel{}
+	if err := c.Get(ctx, req.NamespacedName, infModel); err != nil {
+		if errors.IsNotFound(err) {
+			klog.V(1).Infof("InferenceModel %v not found. Removing from datastore since object must be deleted", req.NamespacedName)
```
Comment (ahg-g) [inline pkg/ext-proc/backend/inferencemodel_reconciler.go:34]: ditto to using debugging levels

**Review by ahg-g — COMMENTED** [review]
a couple of nits to use debugging levels.

File: pkg/ext-proc/backend/inferencemodel_reconciler.go [hunk 3]
```diff
@@ -25,32 +26,37 @@ func (c *InferenceModelReconciler) Reconcile(ctx context.Context, req ctrl.Reque
...
+			c.Datastore.InferenceModels.Delete(infModel.Spec.ModelName)
```
Comment (kfswain) [inline pkg/ext-proc/backend/inferencemodel_reconciler.go:35]: I'm a little worried about doing this, but maybe it's unfounded. 

My concern is that if for some reason there is a small lapse in communication with the API server, we could remove the inference model from the list of available models until the next reconciliation event (i believe the max time is 10 min, assuming there is no event that triggers reconciliation) So in the worst case, we could knock down a users service for 10 min, and then it pops back up unexpectedly, making for a rather nasty heisenbug. Its unfortunate that controller runtime doesnt let you separate by delete/create/update events, this would be much more easily remedied.

WDYT?

**Review by kfswain — COMMENTED** [review]
Mostly LGTM, have a comment wrt approach. Would like to close the loop there before we move forward.

File: pkg/ext-proc/backend/inferencemodel_reconciler.go (hunk 3 above)
Comment (kfswain) [reply pkg/ext-proc/backend/inferencemodel_reconciler.go:35]: Should we instead just not return the err? As I believe that causes controller runtime to requeue the reconciliation obj. But that could lead to the issue of leaving up an IM that doesnt actually exist (granted we currently have that issue) 

for the long term we could (not this PR):

- We would then have to use: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/builder#TypedBuilder.WithEventFilter i think we could do something messy by making some sort of `cleanupReconciler`. 

- We could also just switch to listing the infModels per request and using the informer cache to do so.

- But also its handled well in the non-controller runtime paradigm: https://github.com/kubernetes/sample-controller/blob/master/controller.go#L152

Comment (ahg-g) [reply pkg/ext-proc/backend/inferencemodel_reconciler.go:35]: We also need to check for deletionTimestamp and remove the InferenceModel if set.

Taking a step back, do we actually need an inferenceModel reconciler? do we need to store the inferenceModel objects ourselves? If not, I think we can drop it and just `Get` it (controller-runtime has an informer cache underneath).

Comment (ahg-g) [reply pkg/ext-proc/backend/inferencemodel_reconciler.go:35]: @kfswain we can setup a handlers for delete/create/update with controller-runtime, see for example kueue: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/core/resourceflavor_controller.go#L145

Comment (kfswain) [reply pkg/ext-proc/backend/inferencemodel_reconciler.go:35]: > We also need to check for deletionTimestamp and remove the InferenceModel if set.
> 
> Taking a step back, do we actually need an inferenceModel reconciler? do we need to store the inferenceModel objects ourselves? If not, I think we can drop it and just `Get` it (controller-runtime has an informer cache underneath).

I was thinking about that also, were we to ever set up fairness, we would need to hold on to these objects, or at least their name as the key value for a cache of traffic data. Otherwise we could fetch as needed as long as its using a cache and not blasting the api-server.  But is it any better than what we would do here?

Comment (ahg-g) [reply pkg/ext-proc/backend/inferencemodel_reconciler.go:35]: yeah, we need that for fairness, we should keep it.

I think we need to setup a Delete handler to reliably delete the object from the store just like we do with Kueue.

Comment (kfswain) [reply pkg/ext-proc/backend/inferencemodel_reconciler.go:35]: Definitely agreed there. Made: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/310.

I think for this PR we can reduce the logging noise, and then have a separate PR addressing deletion events. 

Is that fair?

Comment (ahg-g) [reply pkg/ext-proc/backend/inferencemodel_reconciler.go:35]: sg

File: pkg/ext-proc/backend/inferencemodel_reconciler.go (hunk 1 above)
Comment (ahg-g) [reply pkg/ext-proc/backend/inferencemodel_reconciler.go:29]: sg, lets merge this and follow up with a PR for the logging levels.

**Comment by ahg-g** [comment]
Sent https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/317 which should allow the failed test to pass
