### PR TITLE
Defining an outer metadata struct as part of the extproc endpoint picking protocol

### LINKED ISSUE #298: Contract between Envoy Extproc and EPP is incorrect.
**What happened**:
 Envoy expects that the first field in the metadata should match the receiving namespace of the envoy extproc configuration. The data should be wrapped within the struct of this namespace key.

**What you expected to happen**:
The struct containing the key value for "IP:PORT" should be contained in the namespace key.

### PR DESCRIPTION
**Pull request by ahg-g**
Fixes #298 

/hold

### CODE REVIEW

File: cmd/epp/main.go [hunk 1]
```diff
@@ -67,7 +67,12 @@ var (
 	targetEndpointKey = flag.String(
 		"targetEndpointKey",
 		runserver.DefaultTargetEndpointKey,
-		"Header key used by Envoy to route to the appropriate pod. This must match Envoy configuration.")
+		"Header and response metadata key used by Envoy to route to the appropriate pod. This must match Envoy configuration.")
+	targetEndpointOuterMetadataKey = flag.String(
+		"TargetEndpointOuterMetadataKey",
```
Comment (hzxuzhonghu) [inline cmd/epp/main.go:72]: It represents the receiving namespace of envoy, i think the name is a little confusing

File: docs/proposals/003-endpoint-picker-protocol/README.md [hunk 2]
```diff
@@ -12,7 +12,9 @@ The EPP MUST implement the Envoy
...
 
 For each HTTP request, the EPP MUST communicate to the proxy the picked model server endpoint, via
-adding the `x-gateway-destination-endpoint` HTTP header in the request and as an unstructured entry in the [dynamic_metadata](https://github.com/envoyproxy/go-control-plane/blob/c19bf63a811c90bf9e02f8e0dc1dcef94931ebb4/envoy/service/ext_proc/v3/external_processor.pb.go#L320) field of the ext-proc response, or otherwise return an error. The EPP MUST not set two different values in the header and the response metadata. 
+adding the `x-gateway-destination-endpoint` HTTP header in the request and as an unstructured entry in the [dynamic_metadata](https://github.com/envoyproxy/go-control-plane/blob/c19bf63a811c90bf9e02f8e0dc1dcef94931ebb4/envoy/service/ext_proc/v3/external_processor.pb.go#L320) field of the ext-proc response, or otherwise return an error. The metadata entry for the picked endpoint MUST be wrapped with an outer key named `gateway-destination-endpoint.dynamic_forwarding.selected_endpoints`.
+
+The EPP MUST not set two different values in the header and the response metadata.
```
Comment (LiorLieberman) [inline docs/proposals/003-endpoint-picker-protocol/README.md:17]:
```suggestion
For each HTTP request, the EPP MUST communicate to the proxy the picked model server endpoint via:

1. Setting the `x-gateway-destination-endpoint` HTTP header to the selected endpoint in <ip:port> format.

2. Set an unstructured entry in the [dynamic_metadata](https://github.com/envoyproxy/go-control-plane/blob/c19bf63a811c90bf9e02f8e0dc1dcef94931ebb4/envoy/service/ext_proc/v3/external_processor.pb.go#L320) field of the ext-proc response. The metadata entry for the picked endpoint MUST be wrapped with an outer key (which represents the metadata namespace) with a default of `envoy.lb`.

Note:
- If the EPP did not communicate the server endpoint via these two methods, it MUST return an error.
- The EPP MUST not set two different values in the header and the inner response metadata value. 

### Why envoy.lb namespace as a default? 
The `envoy.lb` namesapce is a predefined namespace used for subsetting. One common way to use the selected endpoint returned from the server, is [envoy subsets](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets) where host metadata for subset load balancing must be placed under `envoy.lb`.
```

File: docs/proposals/003-endpoint-picker-protocol/README.md [hunk 3]
```diff
@@ -12,7 +12,9 @@ The EPP MUST implement the Envoy
 [external processing service](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/ext_proc/v3/external_processor)protocol.
 
 For each HTTP request, the EPP MUST communicate to the proxy the picked model server endpoint, via
```
Comment (LiorLieberman) [inline docs/proposals/003-endpoint-picker-protocol/README.md:14]:
```suggestion
```

I captured this in below suggestion so no need it here anymore

File: docs/proposals/003-endpoint-picker-protocol/README.md [hunk 4]
```diff
@@ -11,8 +11,28 @@ This is the protocol between the EPP and the proxy (e.g, Envoy).
...
+2. Set an unstructured entry in the [dynamic_metadata](https://github.com/envoyproxy/go-control-plane/blob/c19bf63a811c90bf9e02f8e0dc1dcef94931ebb4/envoy/service/ext_proc/v3/external_processor.pb.go#L320) field of the ext-proc response. The metadata entry for the picked endpoint MUST be wrapped with an outer key (which represents the metadata namespace) with a default of `envoy.lb`.
+
+The final metadata necessary would look like: 
+```go
+dynamicMetadata: {
+  "envoy.lb": {
+    "x-gateway-destination-endpoint": <ip:port>"  
+  }
+}
+
```
Comment (LiorLieberman) [inline docs/proposals/003-endpoint-picker-protocol/README.md:27]:
```suggestion
```
```

Comment (ahg-g) [reply docs/proposals/003-endpoint-picker-protocol/README.md]: done

**Review by hzxuzhonghu — COMMENTED** [review]
/lgtm

**Review by AndresGuedez — APPROVED** [review]
LGTM, thanks!
