### PR TITLE
inferencemodel_reconciler: Fix a log message

### LINKED ISSUE #187: Fix InferenceModel Reconciler Log Message
The following log line should have a space between the InferenceMode kind and the namespace/name:

Current:
```
inferencemodel_reconciler.go:27] reconciling InferenceModeldefault/inferencemodel-sample
```

Should be:
```
inferencemodel_reconciler.go:27] reconciling InferenceModel default/inferencemodel-sample
```

### PR DESCRIPTION
**Pull request by tchap**
Fixes #187

### CODE REVIEW

File: pkg/ext-proc/backend/inferencemodel_reconciler.go [hunk 1]
```diff
@@ -25,7 +25,7 @@ func (c *InferenceModelReconciler) Reconcile(ctx context.Context, req ctrl.Reque
 	if req.Namespace != c.PoolNamespacedName.Namespace {
 		return ctrl.Result{}, nil
 	}
-	klog.V(1).Info("reconciling InferenceModel", req.NamespacedName)
+	klog.V(1).Infof("reconciling InferenceModel %v", req.NamespacedName)
```
Comment (ahg-g) [inline pkg/ext-proc/backend/inferencemodel_reconciler.go:28]: can you use the logging levels defined at https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/pkg/ext-proc/util/logging/logging_const.go

It would be great if you can update that for all logging in this file :)

Comment (tchap) [reply pkg/ext-proc/backend/inferencemodel_reconciler.go:28]: Hi, I actually noticed only after this issue that there is #251 . I would honestly just merge this quickly and move on to work on complete migration to the logging guidelines, if you don't mind.
