### PR TITLE
[BBR] Verify EPP/BBR have no cross-imports

### LINKED ISSUE #2411: verify epp/bbr do not have cross imports
today bbr imports epp in some of the files.
inspired by the [verify-framework-imports](https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/main/hack/verify-framework-imports.go), we should create a small program that can run to verify bbr doesn't import epp (and epp doesn't import bbr).
we should allow being strict (fail the script) or just output the violations.

we should then use the output of this script to fix imports and make sure bbr/epp are completely separate.
common code might be extracted to a common package that the two components use. 

after it works we can also integrate it in the CI pipeline to make sure incoming PRs don't break this.

### PR DESCRIPTION
**Pull request by asaadbalum**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Today BBR imports EPP code in several files (`pkg/epp/framework/interface/plugin`). This creates an unintended coupling between two components that should be independent binaries.

This PR adds a verification script to detect and report these cross-imports, following the same `currentCodeExceptionMap` pattern as `verify-framework-imports.go`:

1. **Adds `hack/verify-component-imports.go`**: A verification script (modeled after `verify-framework-imports.go`) that detects cross-imports between `pkg/epp` and `pkg/bbr` using Go AST parsing. Known violations are listed in `currentCodeExceptionMap` and reported as warnings. New violations not in the exception list cause a non-zero exit, blocking PRs that introduce additional cross-imports. The `--strict` flag treats all violations as errors, for use once all exceptions are resolved.
2. **Integrates into CI**: Added `verify-component-imports` target to `make verify`.

Current known exceptions (6 violations, all BBR importing `pkg/epp/framework/interface/plugin`):
- `pkg/bbr/framework/plugins.go`
- `pkg/bbr/handlers/request_test.go`
- `pkg/bbr/handlers/response_test.go`
- `pkg/bbr/plugins/basemodelextractor/base_model_to_header.go`
- `pkg/bbr/plugins/basemodelextractor/base_model_to_header_test.go`
- `pkg/bbr/plugins/bodyfieldtoheader/body_field_to_header.go`

As each violation is fixed in follow-up work, its entry is removed from the map — the list only shrinks over time.

**Which issue(s) this PR fixes**:

Fixes #2411

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by nirrozenbaum — COMMENTED** [review]
@asaadbalum please revert the changes that fix the imports.
current issue is only about having the code to verify imports (fixing them is a different task).

this PR should be mostly the `verify-component-imports`.
then we will take next steps.
it might be different decisions for different things (e.g., plugin definition atm might be duplicated instead of moving to a common package).

**Comment by asaadbalum** [comment]
Done. Reverted all import-fixing changes. The PR now only contains:

1. `hack/verify-component-imports.go` — the verification script
2. `Makefile` — integrating `verify-component-imports` into `make verify`

The script runs in permissive mode by default (reports violations, exits 0). The `--strict` flag is available for CI enforcement once the cross-imports are resolved in follow-up work.

**Review by nirrozenbaum — COMMENTED** [review]
@asaadbalum can we follow the same pattern as verify framework imports where a list of excluded files are specified in a variable?
the thinking is - we want to run in a non-strict mode until all imports are fixed, but at the same time, we want to be able to easily identify a PR that is adding a new forbidden import and block it. so once this script is merged, we have the list of violations and we don't add more violations, we only reduce it one by one.

**Comment by asaadbalum** [comment]
> @asaadbalum can we follow the same pattern as verify framework imports where a list of excluded files are specified in a variable? the thinking is - we want to run in a non-strict mode until all imports are fixed, but at the same time, we want to be able to easily identify a PR that is adding a new forbidden import and block it. so once this script is merged, we have the list of violations and we don't add more violations, we only reduce it one by one.

Updated. The script now follows the same `currentCodeExceptionMap` pattern as `verify-framework-imports.go`:

- Known violations are listed in an explicit map and reported as warnings (exit 0).
- New violations not in the map fail the check (exit 1), blocking PRs that introduce additional cross-imports.
- As violations are fixed, entries are removed from the map — it only shrinks.
- `--strict` mode is available for when all exceptions are resolved.

Also rebased on latest main and updated the exception list to reflect current state (3 violations).

Attaching a screenshot from "pull-gateway-api-inference-extension-verify-main" test:

image

**Comment by ahg-g** [comment]
@nirrozenbaum can you pls take a look?

File: hack/verify-component-imports.go [hunk 1]
```diff
@@ -0,0 +1,230 @@
...
+var currentCodeExceptionMap = map[string][]string{
+	"pkg/bbr/framework/plugins.go": {
+		"pkg/epp/framework/interface/plugin",
+	},
+	"pkg/bbr/plugins/body_field_to_header.go": {
+		"pkg/epp/framework/interface/plugin",
+	},
+	"pkg/bbr/plugins/default.go": {
+		"pkg/epp/framework/interface/plugin",
+	},
```
Comment (nirrozenbaum) [inline hack/verify-component-imports.go:85]: need to revisit these values after some code changes were done in the repo.

**Review by nirrozenbaum — COMMENTED** [review]
@asaadbalum can we revive this PR?
I would like to get this in

File: hack/verify-component-imports.go (hunk 1 above)
Comment (asaadbalum) [reply hack/verify-component-imports.go:85]: Updated, rebased on latest main and refreshed the `currentCodeExceptionMap` to reflect the current 6 BBR-EPP cross-imports.

CI `verify-main` should show:
- 6 warnings (known exceptions)
- `[PASS] No new violations`

**Review by nirrozenbaum — APPROVED** [review]
/lgtm
/approve

**Comment by nirrozenbaum** [comment]
overriding CRD validation (error was triggered due to a different change)
