### PR TITLE
Fix request headers not captured in streaming mode

### LINKED ISSUE #2585: [pluggable bbr] bug in request headers handling: headers are not captured properly
current code for handling request headers includes a bug, the headers are not captured properly in the InferenceRequest. 
https://github.com/kubernetes-sigs/gateway-api-inference-extension/blob/812da04d277eee56556c0340e9ab191a710973c4/pkg/bbr/handlers/server.go#L124-L135

as seen in the above code, if the message is streaming and is not EoS (which is the case when the request includes also a body), the handling logic is skipped. 

we need to mirror the request handling from epp. 
in case it's streaming mode and isn't EoS, we should not return a response (leave it for handling when getting the body, as it is today). 
if it's not streaming OR EoS (which means there is no body for the request), we can return the response.

### PR DESCRIPTION
**Pull request by abdallahsamabd**
/kind bug

**What type of PR is this?**

Bug fix

**What this PR does / why we need it**:

In streaming mode, when a request includes a body, the `HandleRequestHeaders` call was entirely skipped in the `RequestHeaders` case of the ext_proc `Process` loop. This meant request headers were never captured into `reqCtx.Request.Headers`, and the `request-id` was never extracted for structured logging.

This fix ensures that:
1. The `request-id` is always extracted for logging, regardless of streaming mode.
2. `HandleRequestHeaders` is always called to populate `reqCtx.Request.Headers`, so downstream plugins have access to request headers during body processing.
3. In streaming mode, the ext_proc *response* is still deferred (not sent back to Envoy) — only the body processing phase produces the actual response, preserving the existing streaming contract.

**Which issue(s) this PR fixes**:

Fixes #2585

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

File: pkg/bbr/handlers/server.go [hunk 1]
```diff
@@ -122,15 +122,19 @@ func (s *Server) Process(srv extProcPb.ExternalProcessor_ProcessServer) error {
...
-				// If streaming and the body is not empty, then headers are handled when processing request body.
-				loggerVerbose.Info("Received headers, passing off header processing until body arrives...")
-			} else {
-				if requestId := envoy.ExtractHeaderValue(v, reqcommon.RequestIdHeaderKey); len(requestId) > 0 {
-					logger = logger.WithValues(reqcommon.RequestIdHeaderKey, requestId)
-					loggerVerbose = logger.V(logutil.VERBOSE)
-					ctx = log.IntoContext(ctx, logger)
+				// Capture headers now, but defer the response until body arrives.
+				if _, err := s.HandleRequestHeaders(reqCtx, v.RequestHeaders); err != nil {
+					logger.Error(err, "Failed to capture request headers")
```
Comment (nirrozenbaum) [inline pkg/bbr/handlers/server.go]: no need for this log line. it will be logged after the switch

File: pkg/bbr/handlers/server.go [hunk 2]
```diff
@@ -122,15 +122,19 @@ func (s *Server) Process(srv extProcPb.ExternalProcessor_ProcessServer) error {
...
 				}
```
Comment (nirrozenbaum) [inline pkg/bbr/handlers/server.go]: maybe just call the function and assign returned err value?
```suggestion
				_, err := s.HandleRequestHeaders(reqCtx, v.RequestHeaders)
```

Comment (abdallahsamabd) [reply pkg/bbr/handlers/server.go]: done thanks
