### PR TITLE
[Fix] Support prompt array for `/completions` request

### LINKED ISSUE #2721: Support OpenAI prompt variations in `/completions` endpoint (match client)
**What happened**:
OpenAI requests for `/v1/completions` fail as `Bad Request` in EPP when the prompt is `[]string`.

**What you expected to happen**:
Requests for completions should allow all OpenAI options.
The struct definition in pkg/epp/framework/interface/scheduling/types.go:L140:
```go
// CompletionsRequest is a structured representation of the fields we parse out of the /v1/completions request
// body. For detailed body fields, please refer to https://platform.openai.com/docs/api-reference/completions.
// This struct includes fields usable for plugins and scheduling decisions - and not the entire
// API spec.
type CompletionsRequest struct {
	// Prompt is the prompt that was sent in the request body.
	Prompt string `json:"prompt,omitempty"`
	// CacheSalt is an optional request parameter to isolate prefix caches for security reasons.
	CacheSalt string `json:"cache_salt,omitempty"`
}
```
OpenAI spec / Python code accepts an array of prompts in 
https://github.com/openai/openai-python/blob/main/src/openai/types/completion_create_params.py:
```md
 The prompt(s) to generate completions for, encoded as a string, array of 
    strings, array of tokens, or array of token arrays.
```

**How to reproduce it (as minimally and precisely as possible)**:
Send request with multiple, comma separated, string in the prompt. See example in comments below.

**Anything else we need to know?**:

**Environment**:
N/A

### PR DESCRIPTION
**Pull request by elevran**
**What type of PR is this?**
/kind bug
/kind feature

**What this PR does / why we need it**:
According to the OpenAI client implement, the request `Prompt` field can be either `string` or `[]string`.
Currently, requests with prompt which is an array of strings fail with Bad Request.

The PR introduces a Prompt object which supports both string and string array. We do not introduce token (and token array) prompt types.
The PR covers the base type, marshalling and simple replacements for callers to test if empty and length (for token estimation) which operate over both string and []string options.

**Which issue(s) this PR fixes**:
Fixes #2721 

**Does this PR introduce a user-facing change?**:
```release-note
Allow both string and string array for prompt in Completions request.
```

### CODE REVIEW

File: pkg/epp/framework/interface/scheduling/types.go [hunk 1]
```diff
@@ -145,13 +145,52 @@ func (r *LLMRequestBody) CacheSalt() string {
...
+
 // CompletionsRequest is a structured representation of the fields we parse out of the /v1/completions request
 // body. For detailed body fields, please refer to https://platform.openai.com/docs/api-reference/completions.
 // This struct includes fields usable for plugins and scheduling decisions - and not the entire
 // API spec.
 type CompletionsRequest struct {
-	// Prompt is the prompt that was sent in the request body.
-	Prompt string `json:"prompt,omitempty"`
+	// Prompt is the prompt(s) sent in the request body; can be a string or an array of strings.
+	Prompt Prompt `json:"prompt"`
```
Comment (ahg-g) [inline pkg/epp/framework/interface/scheduling/types.go:220]: @zetxqx the internal `LLMRequestBody` type is still tightly coupled with openai format, we should completely decouple that and limit the OAI spec to the OAI parser only.

Comment (ahg-g) [reply pkg/epp/framework/interface/scheduling/types.go:220]: https://github.com/kubernetes-sigs/gateway-api-inference-extension/issues/2731

**Comment by elevran** [comment]
@ahg-g this needs /lgtm to merge or waiting on additional feedback?

**Comment by ahg-g** [comment]
ah, sorry, I missed it, needs another rebase

**Comment by elevran** [comment]
@ahg-g rebased on latest
